export const longStrings = {
  PublicCharDesc:
    "To protect security and user rights, we update hoyolab role data through the user's device (client) rather than through the server. This means that if a user does not use Stargazer for a while, it may result in discrepancies in their character count, days active, achievements achieved, and the Forgotten Hall data. Please note that these data are for reference only and are not accurate.",
  TrailblazerNotiTaggedU:
    'Player ${1} in "${2}\'s Discussion" has mentioned you! Come to join the discussion.',
  UIDOnlySupportFullUID:
    "Only support search by full UID, it's not allow to search by name or partly UID.",
  LoginViaPCToGetCookies:
    "Please use a computer to log in to hoyolab / 米游社. Make sure you have logout, and login again, then please follow the video tutorial: https://www.youtube.com/watch?v=CLkhV30kg_A (for copying, please select cURL (bash))",
  SelectServerAndPasteCookies:
    "Please select the server and paste your Cookies.",
  CommentOverLimit:
    "The input exceeds the maximum limit (200 characters), please reduce the input before posting.",
  DonationRemoveAds: "Made by Coding Band :D",
  AboutTheAppContent:
    "<h2>About Stargazer 2</h2><div>Stargazer 2 is a third-party Star Rail assistant application developed by Coding Band. It provides functions such as proficiency inquiry, character illustration, performance inquiry, ranking list, etc... <br> We aim to create a Star Rail Assistant App with native, mobile experience to provide a more convenient and smooth usage experience.</div><br><h2>About Team</h2><div>Coding Band is a development team that focuses on developing practicality, delving into the art and fun of software, and currently consists of three core members:</div><div><li>2O48: UI/UX Designer, art reviewer </li><li>Dalufish: Chief Engineer, full-end development </li><li>Voc-夜芷冰：Project Manager, full-end development </li></div><h2>Special Thanks</h2><div> Special thanks to 明治and all closed beta testers for helping us improve during the closed beta period.<br>jedudu<br>yi_9487<br>appledush#0218<br>shiroweaver<br>_7475<br>rxin.66<br>rover5205<br>rudmon<br>.yanyi<br>mo_yc<br>ryouendragon3369<br>jonahs0202<br>mashujiu<br>yangyangxd<br>sava_tw<br>日輪#1577<br>.yangqin<br>sakura_snow.0w0<br>professionalwindowsexpert<br>dreamawake<br>_d_evil_<br>whitykun<br><br>Stargazer 2 would not have been released in two months without your help :D</div><h2>Warm Reminder</h2><div>Please note that, this project and application do not belong to miHoYo Co., Ltd. and have not been approved. Stargazer 2 is only a project that provides data developed by fans. The information provided in this app is for reference only. Stargazer 2 will not guarantee the accuracy and completeness of any information it contains to any degree. <br><br> The copyright of each material used in the 'Stargazer 2' project belongs to the copyright holder.<br> The copyright of the 'Stargazer 2' project code belongs to Coding Band. </div><br> Some of the materials used in this project come from the following websites <br>https://starrailstation.com/<br>https://github.com/reko-beep/hsr-data<br>https://honkai-star-rail.fandom.com/wiki/Honkai:_Star_Rail_Wiki<br>https://wiki.biligame.com/sr/首页<br>https://www.prydwen.gg/star-rail<br>https://api.mihomo.me/<br>https://github.com/Mar-7th",
  IOSCantLoginYet:
    "Due to technical limitations of the iOS platform, login is currently only possible through the use of cookies. We sincerely apologize for the inconvenience caused >_<",
  LoginHint:
    "Please note that: 1. Currently, only Hoyoverse, Miyoushe and Cookies can operate normally. If you try to log in with Google or Facebook, unexpected errors may occur. Therefore, we recommend that you change the account binding in the game to get the best experience. 2. Due to platform limitations, iOS currently only supports cookie login. We apologize for the inconvenience caused.",
  LoginPolicy:
    "<p>Dear user, logging in to the Miyoushe/Hoyoverse account function requires your cookies to be stored on the device, so we must obtain your authorization before we can proceed. We guarantee that your cookies will only be saved locally and used only between you and 米遊社/Hoyoverse. In addition, we will also store game data (but not cookies) on the server to provide services (such as MOC ranking).</p><br/><p>Note: First, we cannot obtain the account and password information you enter. Entering the account password is only used to provide a more convenient way to obtain cookies, replacing the inconvenience of manually searching and entering cookies. Second, we ensure that cookies are only stored on the user device (client) (whether obtained manually or through the login page). You can view the relevant source code in Stargazer's GitHub repository to verify this message. Therefore, we will not be responsible for the theft of any user's account password.",
    GithubStarPlease: "If you think this project is helpful, please give us a star in GitHub, thx!",

  };
