#Wed Jul 10 12:39:52 HKT 2024
android.nonTransitiveRClass=true
APP_VERSION_CODENAME=Dan Heng
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding\=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
APP_VERSION=2.3.2
android.useAndroidX=true
APP_VERSION_CODENAME_BETA=Echo
APP_VERSION_BETA=2.4.0
kotlin.code.style=official
APP_VERSION_CODE=3686
kotlin.mpp.enableCInteropCommonization=true
APP_PROFILE=PRODUCTION
APP_PLATFORM=Android
