#Thu Jan 02 21:32:03 HKT 2025
APP_PLATFORM=Android
APP_PROFILE=PRODUCTION
APP_VERSION=2025.01.02
APP_VERSION_CODE=6166
APP_VERSION_CODENAME=SG3
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding\=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
xcodeproj=~/iosApp
