#Mon Jan 06 17:52:33 HKT 2025
APP_PLATFORM=Android
APP_PROFILE=PRODUCTION
APP_VERSION=2025.01.06
APP_VERSION_BETA=2.4.6
APP_VERSION_CODE=5628
APP_VERSION_CODENAME=SG3
APP_VERSION_CODENAME_BETA=Echo
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding\=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
xcodeproj=~/iosApp
