export const longStrings = {
    PublicCharDesc: "To protect security and user rights, we update hoyolab role data through the user's device (client) rather than through the server. This means that if a user does not use Stargazer for a while, it may result in discrepancies in their character count, days active, achievements achieved, and the Forgotten Hall data. Please note that these data are for reference only and are not accurate.",
    TrailblazerNotiTaggedU: "Player ${1} in \"${2}'s Discussion\" has mentioned you! Come to join the discussion.",
    UIDOnlySupportFullUID:"Only support search by full UID, it's not allow to search by name or partly UID.",
    LoginViaPCToGetCookies:"Please use a computer to log in to Hoyolab / Miyoushe, press F12 to open the developer panel -> Applications -> Cookies, and paste the Cookies that contain ltuid_v2, ltoken_v2, account_id_v2, cookie_token_v2, account_mid_v2 and ltmid_v2. Note that this option is primarily designed for developers. Stargazer recommends that you do not use this option unless necessary, to avoid adding complexity.",
    SelectServerAndPasteCookies: "Please select the server and paste your Cookies.",
    CommentOverLimit: "The input exceeds the maximum limit (200 characters), please reduce the input before posting.",
    DonationRemoveAds: "Remove Ads through donation or invite others",
    AboutTheAppContent:"<h2>About Stargazer 2</h2><div>Stargazer 2 is a third-party Star Rail assistant application developed by Coding Band. It provides functions such as proficiency inquiry, character illustration, performance inquiry, ranking list, etc... <br> We aim to create a Star Rail Assistant App with native, mobile experience to provide a more convenient and smooth usage experience.</div><br><h2>About Team</h2><div>Coding Band is a development team that focuses on developing practicality, delving into the art and fun of software, and currently consists of three core members:</div><div><li>2O48: UI/UX Designer, art reviewer </li><li>Dalufish: Chief Engineer, full-end development </li><li>Voc-夜芷冰：Project Manager, full-end development </li></div><h2>Special Thanks</h2><div> Special thanks to 明治and all closed beta testers for helping us improve during the closed beta period.<br>jedudu<br>yi_9487<br>appledush#0218<br>shiroweaver<br>_7475<br>rxin.66<br>rover5205<br>rudmon<br>.yanyi<br>mo_yc<br>ryouendragon3369<br>jonahs0202<br>mashujiu<br>yangyangxd<br>sava_tw<br>日輪#1577<br>.yangqin<br>sakura_snow.0w0<br>professionalwindowsexpert<br>dreamawake<br>_d_evil_<br>whitykun<br><br>Stargazer 2 would not have been released in two months without your help :D</div><h2>Warm Reminder</h2><div>Please note that, this project and application do not belong to miHoYo Co., Ltd. and have not been approved. Stargazer 2 is only a project that provides data developed by fans. The information provided in this app is for reference only. Stargazer 2 will not guarantee the accuracy and completeness of any information it contains to any degree. <br><br> The copyright of each material used in the 'Stargazer 2' project belongs to the copyright holder.<br> The copyright of the 'Stargazer 2' project code belongs to Coding Band. </div><br> Some of the materials used in this project come from the following websites <br>https://starrailstation.com/<br>https://github.com/reko-beep/hsr-data<br>https://honkai-star-rail.fandom.com/wiki/Honkai:_Star_Rail_Wiki<br>https://wiki.biligame.com/sr/首页<br>https://www.prydwen.gg/star-rail<br>https://api.mihomo.me/<br>https://github.com/Mar-7th"
}