[versions]
adaptive = "1.1.0"
agp = "8.10.1"
android-compileSdk = "35"
android-minSdk = "26"
android-targetSdk = "35"
androidx-activityCompose = "1.10.1"
coil = "3.3.0"
compose-plugin = "1.9.0"
composeBoxshadow = "0.2.2"
composeDropshadow = "0.2.2"
composeWebviewMultiplatform = "1.9.40"
fastscrollerCore = "0.3.2"
fastscrollerMaterial3 = "0.3.2"
fastscrollerIndicator = "0.3.2"
grid = "2.1.0"
haze = "1.6.10"
kmpIo = "0.1.6"
kotlin = "2.2.10"
kotlinxDatetime = "0.6.0"
kotlinxSerializationJson = "1.8.1"
ktorClientCio = "3.3.0"
ktorClientContentNegotiation = "3.3.0"
ktorClientCore = "3.3.0"
ktorClientSerialization = "3.3.0"
material3Android = "1.4.0"
multiplatformSettings = "1.1.1"
multiplatformSettingsNoArg = "1.1.1"
navigationCompose = "2.9.0"
okio = "3.9.1"
precompose = "1.7.0-alpha03"
richeditorCompose = "1.0.0-rc08"
sonner = "0.3.8"
purchases-kmp = "1.7.2+13.26.0"
reorderable = "2.4.3"

[libraries]
# Coil dependencies
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

# Compose dependencies
adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
compose-dropshadow = { module = "io.github.kubode.compose.shadow:compose-dropshadow", version.ref = "composeDropshadow" }
compose-boxshadow = { module = "io.github.kubode.compose.shadow:compose-boxshadow", version.ref = "composeBoxshadow" }
compose-webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "composeWebviewMultiplatform" }
fastscroller-indicator = { module = "io.github.oikvpqya.compose.fastscroller:fastscroller-indicator", version.ref = "fastscrollerIndicator" }
fastscroller-material3 = { module = "io.github.oikvpqya.compose.fastscroller:fastscroller-material3", version.ref = "fastscrollerMaterial3" }
fastscroller-core = { module = "io.github.oikvpqya.compose.fastscroller:fastscroller-core", version.ref = "fastscrollerCore" }
grid = { module = "com.cheonjaeung.compose.grid:grid", version.ref = "grid" }
kmp-io = { module = "io.github.skolson:kmp-io", version.ref = "kmpIo" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
tlaster-precompose = { module = "moe.tlaster:precompose", version.ref = "precompose" }

# Android dependencies
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

# Kotlin dependencies
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationJson" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Ktor dependencies
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientCio" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktorClientSerialization" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientContentNegotiation" }

# Multiplatform Settings dependencies
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettingsNoArg" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }

# Other dependencies
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
richeditor-compose = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditorCompose" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }
purchases-core = { module = "com.revenuecat.purchases:purchases-kmp-core", version.ref = "purchases-kmp" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }