const Character = {
  Argenti: {
    icon: require("../../images/character_icon/argenti_icon.webp"),
    imageFull: require("../../images/character_splash/argenti_splash.webp"),
    eidolon1: require("../../images/character_eidolon/argenti_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/argenti_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/argenti_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/argenti_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/argenti_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/argenti_eidolon6.webp"),
  },
  Huohuo: {
    icon: require("../../images/character_icon/huohuo_icon.webp"),
    imageFull: require("../../images/character_full/huohuo_full.webp"),
    eidolon1: require("../../images/character_eidolon/huohuo_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/huohuo_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/huohuo_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/huohuo_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/huohuo_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/huohuo_eidolon6.webp"),
  },
  "Dan Heng • Imbibitor Lunae": {
    icon: require("../../images/character_icon/dan_heng_il_icon.webp"),
    imageFull: require("../../images/character_splash/dan_heng_il_splash.webp"),
    eidolon1: require("../../images/character_eidolon/dan_heng_il_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/dan_heng_il_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/dan_heng_il_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/dan_heng_il_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/dan_heng_il_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/dan_heng_il_eidolon6.webp"),
  },
  Jingliu: {
    icon: require("../../images/character_icon/jingliu_icon.webp"),
    imageFull: require("../../images/character_full/jingliu_full.webp"),
    eidolon1: require("../../images/character_eidolon/jingliu_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/jingliu_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/jingliu_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/jingliu_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/jingliu_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/jingliu_eidolon6.webp"),
  },
  Bailu: {
    icon: require("../../images/character_icon/bailu_icon.webp"),
    imageFull: require("../../images/character_full/bailu_full.webp"),
    eidolon1: require("../../images/character_eidolon/bailu_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/bailu_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/bailu_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/bailu_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/bailu_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/bailu_eidolon6.webp"),
  },
  Yanqing: {
    icon: require("../../images/character_icon/yanqing_icon.webp"),
    imageFull: require("../../images/character_full/yanqing_full.webp"),
    eidolon1: require("../../images/character_eidolon/yanqing_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/yanqing_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/yanqing_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/yanqing_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/yanqing_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/yanqing_eidolon6.webp"),
  },
  "Fu Xuan": {
    icon: require("../../images/character_icon/fu_xuan_icon.webp"),
    imageFull: require("../../images/character_splash/fu_xuan_splash.webp"),
    eidolon1: require("../../images/character_eidolon/fu_xuan_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/fu_xuan_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/fu_xuan_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/fu_xuan_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/fu_xuan_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/fu_xuan_eidolon6.webp"),
  },
  Blade: {
    icon: require("../../images/character_icon/blade_icon.webp"),
    imageFull: require("../../images/character_full/blade_full.webp"),
    eidolon1: require("../../images/character_eidolon/blade_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/blade_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/blade_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/blade_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/blade_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/blade_eidolon6.webp"),
  },
  "Jing Yuan": {
    icon: require("../../images/character_icon/jing_yuan_icon.webp"),
    imageFull: require("../../images/character_splash/jing_yuan_splash.webp"),
    eidolon1: require("../../images/character_eidolon/jing_yuan_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/jing_yuan_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/jing_yuan_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/jing_yuan_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/jing_yuan_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/jing_yuan_eidolon6.webp"),
  },
  Luocha: {
    icon: require("../../images/character_icon/luocha_icon.webp"),
    imageFull: require("../../images/character_splash/luocha_splash.webp"),
    eidolon1: require("../../images/character_eidolon/luocha_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/luocha_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/luocha_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/luocha_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/luocha_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/luocha_eidolon6.webp"),
  },
  "Topaz & Numby": {
    icon: require("../../images/character_icon/topaz_icon.webp"),
    imageFull: require("../../images/character_splash/topaz_splash.webp"),
    eidolon1: require("../../images/character_eidolon/topaz_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/topaz_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/topaz_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/topaz_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/topaz_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/topaz_eidolon6.webp"),
  },
  Clara: {
    icon: require("../../images/character_icon/clara_icon.webp"),
    imageFull: require("../../images/character_full/clara_full.webp"),
    eidolon1: require("../../images/character_eidolon/clara_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/clara_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/clara_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/clara_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/clara_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/clara_eidolon6.webp"),
  },
  Gepard: {
    icon: require("../../images/character_icon/gepard_icon.webp"),
    imageFull: require("../../images/character_full/gepard_full.webp"),
    eidolon1: require("../../images/character_eidolon/gepard_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/gepard_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/gepard_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/gepard_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/gepard_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/gepard_eidolon6.webp"),
  },
  Seele: {
    icon: require("../../images/character_icon/seele_icon.webp"),
    imageFull: require("../../images/character_full/seele_full.png"),
    eidolon1: require("../../images/character_eidolon/seele_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/seele_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/seele_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/seele_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/seele_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/seele_eidolon6.webp"),
  },
  Bronya: {
    icon: require("../../images/character_icon/bronya_icon.webp"),
    imageFull: require("../../images/character_full/bronya_full.webp"),
    eidolon1: require("../../images/character_eidolon/bronya_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/bronya_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/bronya_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/bronya_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/bronya_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/bronya_eidolon6.webp"),
  },
  "Silver Wolf": {
    icon: require("../../images/character_icon/silver_wolf_icon.webp"),
    imageFull: require("../../images/character_full/silver_wolf_full.webp"),
    eidolon1: require("../../images/character_eidolon/silver_wolf_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/silver_wolf_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/silver_wolf_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/silver_wolf_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/silver_wolf_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/silver_wolf_eidolon6.webp"),
  },
  Kafka: {
    icon: require("../../images/character_icon/kafka_icon.webp"),
    imageFull: require("../../images/character_full/kafka_full.webp"),
    eidolon1: require("../../images/character_eidolon/kafka_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/kafka_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/kafka_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/kafka_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/kafka_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/kafka_eidolon6.webp"),
  },
  Welt: {
    icon: require("../../images/character_icon/welt_icon.webp"),
    imageFull: require("../../images/character_splash/welt_splash.webp"),
    eidolon1: require("../../images/character_eidolon/welt_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/welt_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/welt_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/welt_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/welt_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/welt_eidolon6.webp"),
  },
  Himeko: {
    icon: require("../../images/character_icon/himeko_icon.webp"),
    imageFull: require("../../images/character_full/himeko_full.webp"),
    eidolon1: require("../../images/character_eidolon/himeko_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/himeko_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/himeko_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/himeko_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/himeko_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/himeko_eidolon6.webp"),
  },
  Hanya: {
    icon: require("../../images/character_icon/hanya_icon.webp"),
    imageFull: require("../../images/character_splash/hanya_splash.webp"),
    eidolon1: require("../../images/character_eidolon/hanya_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/hanya_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/hanya_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/hanya_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/hanya_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/hanya_eidolon6.webp"),
  },
  Guinaifen: {
    icon: require("../../images/character_icon/guinaifen_icon.webp"),
    imageFull: require("../../images/character_splash/guinaifen_splash.webp"),
    eidolon1: require("../../images/character_eidolon/guinaifen_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/guinaifen_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/guinaifen_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/guinaifen_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/guinaifen_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/guinaifen_eidolon6.webp"),
  },
  Yukong: {
    icon: require("../../images/character_icon/yukong_icon.webp"),
    imageFull: require("../../images/character_splash/yukong_splash.webp"),
    eidolon1: require("../../images/character_eidolon/yukong_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/yukong_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/yukong_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/yukong_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/yukong_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/yukong_eidolon6.webp"),
  },
  Sushang: {
    icon: require("../../images/character_icon/sushang_icon.webp"),
    imageFull: require("../../images/character_full/sushang_full.png"),
    eidolon1: require("../../images/character_eidolon/sushang_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/sushang_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/sushang_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/sushang_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/sushang_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/sushang_eidolon6.webp"),
  },
  Tingyun: {
    icon: require("../../images/character_icon/tingyun_icon.webp"),
    imageFull: require("../../images/character_full/tingyun_full.webp"),
    eidolon1: require("../../images/character_eidolon/tingyun_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/tingyun_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/tingyun_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/tingyun_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/tingyun_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/tingyun_eidolon6.webp"),
  },
  Qingque: {
    icon: require("../../images/character_icon/qingque_icon.webp"),
    imageFull: require("../../images/character_full/qingque_full.webp"),
    eidolon1: require("../../images/character_eidolon/qingque_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/qingque_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/qingque_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/qingque_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/qingque_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/qingque_eidolon6.webp"),
  },
  Luka: {
    icon: require("../../images/character_icon/luka_icon.webp"),
    imageFull: require("../../images/character_splash/luka_splash.webp"),
    eidolon1: require("../../images/character_eidolon/luka_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/luka_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/luka_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/luka_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/luka_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/luka_eidolon6.webp"),
  },
  Lynx: {
    icon: require("../../images/character_icon/lynx_icon.webp"),
    imageFull: require("../../images/character_splash/lynx_splash.webp"),
    eidolon1: require("../../images/character_eidolon/lynx_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/lynx_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/lynx_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/lynx_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/lynx_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/lynx_eidolon6.webp"),
  },
  Hook: {
    icon: require("../../images/character_icon/hook_icon.webp"),
    imageFull: require("../../images/character_full/hook_full.webp"),
    eidolon1: require("../../images/character_eidolon/hook_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/hook_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/hook_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/hook_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/hook_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/hook_eidolon6.webp"),
  },
  Sampo: {
    icon: require("../../images/character_icon/sampo_icon.webp"),
    imageFull: require("../../images/character_full/sampo_full.webp"),
    eidolon1: require("../../images/character_eidolon/sampo_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/sampo_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/sampo_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/sampo_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/sampo_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/sampo_eidolon6.webp"),
  },
  Pela: {
    icon: require("../../images/character_icon/pela_icon.webp"),
    imageFull: require("../../images/character_full/pela_full.webp"),
    eidolon1: require("../../images/character_eidolon/pela_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/pela_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/pela_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/pela_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/pela_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/pela_eidolon6.webp"),
  },
  Natasha: {
    icon: require("../../images/character_icon/natasha_icon.webp"),
    imageFull: require("../../images/character_full/natasha_full.webp"),
    eidolon1: require("../../images/character_eidolon/natasha_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/natasha_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/natasha_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/natasha_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/natasha_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/natasha_eidolon6.webp"),
  },
  Serval: {
    icon: require("../../images/character_icon/serval_icon.webp"),
    imageFull: require("../../images/character_full/serval_full.webp"),
    eidolon1: require("../../images/character_eidolon/serval_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/serval_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/serval_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/serval_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/serval_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/serval_eidolon6.webp"),
  },
  Herta: {
    icon: require("../../images/character_icon/herta_icon.webp"),
    imageFull: require("../../images/character_full/herta_full.webp"),
    eidolon1: require("../../images/character_eidolon/herta_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/herta_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/herta_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/herta_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/herta_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/herta_eidolon6.webp"),
  },
  Asta: {
    icon: require("../../images/character_icon/asta_icon.webp"),
    imageFull: require("../../images/character_full/asta_full.webp"),
    eidolon1: require("../../images/character_eidolon/asta_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/asta_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/asta_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/asta_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/asta_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/asta_eidolon6.webp"),
  },
  Arlan: {
    icon: require("../../images/character_icon/arlan_icon.webp"),
    imageFull: require("../../images/character_full/arlan_full.webp"),
    eidolon1: require("../../images/character_eidolon/arlan_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/arlan_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/arlan_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/arlan_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/arlan_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/arlan_eidolon6.webp"),
  },
  "Dan Heng": {
    icon: require("../../images/character_icon/dan_heng_icon.webp"),
    imageFull: require("../../images/character_full/dan_heng_full.webp"),
    eidolon1: require("../../images/character_eidolon/dan_heng_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/dan_heng_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/dan_heng_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/dan_heng_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/dan_heng_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/dan_heng_eidolon6.webp"),
  },
  "March 7th": {
    icon: require("../../images/character_icon/march_7th_icon.webp"),
    imageFull: require("../../images/character_full/march_7th_full.webp"),
    eidolon1: require("../../images/character_eidolon/march_7th_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/march_7th_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/march_7th_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/march_7th_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/march_7th_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/march_7th_eidolon6.webp"),
  },
};

export default Character;
