const CharacterImage: any = {
  //add in 2.1.0
  "Acheron": {
    icon: require("../../images/character_icon/acheron_icon.webp"),
    imageSplash: require("../../images/character_splash/acheron_splash.webp"),
    imageFull: require("../../images/character_full/acheron_full.webp"),
    fade: require("../../images/character_fade/acheron_fade.webp"),
  },
  "Aventurine": {
    icon: require("../../images/character_icon/aventurine_icon.webp"),
    imageSplash: require("../../images/character_splash/aventurine_splash.webp"),
    imageFull: require("../../images/character_full/aventurine_full.webp"),
    fade: require("../../images/character_fade/aventurine_fade.webp"),
  },
  "Gallagher": {
    icon: require("../../images/character_icon/gallagher_icon.webp"),
    imageSplash: require("../../images/character_splash/gallagher_splash.webp"),
    imageFull: require("../../images/character_full/gallagher_full.webp"),
    fade: require("../../images/character_fade/gallagher_fade.webp"),
  },
  //add in 2.0.0
  "Black Swan": {
    icon: require("../../images/character_icon/black_swan_icon.webp"),
    imageSplash: require("../../images/character_splash/black_swan_splash.webp"),
    imageFull: require("../../images/character_full/black_swan_full.webp"),
    fade: require("../../images/character_fade/black_swan_fade.webp"),
  },
  "Sparkle": {
    icon: require("../../images/character_icon/sparkle_icon.webp"),
    imageSplash: require("../../images/character_splash/sparkle_splash.webp"),
    imageFull: require("../../images/character_full/sparkle_full.webp"),
    fade: require("../../images/character_fade/sparkle_fade.webp"),
  },
  "Misha": {
    icon: require("../../images/character_icon/misha_icon.webp"),
    imageSplash: require("../../images/character_splash/misha_splash.webp"),
    imageFull: require("../../images/character_full/misha_full.webp"),
    fade: require("../../images/character_fade/misha_fade.webp"),
  },
  //add in 1.6.0
  "Dr. Ratio": {
    icon: require("../../images/character_icon/dr_ratio_icon.webp"),
    imageSplash: require("../../images/character_splash/dr_ratio_splash.webp"),
    imageFull: require("../../images/character_full/dr_ratio_full.webp"),
    fade: require("../../images/character_fade/dr_ratio_fade.webp"),
  },
  "Ruan Mei": {
    icon: require("../../images/character_icon/ruan_mei_icon.webp"),
    imageSplash: require("../../images/character_splash/ruan_mei_splash.webp"),
    imageFull: require("../../images/character_full/ruan_mei_full.webp"),
    fade: require("../../images/character_fade/ruan_mei_fade.webp"),
  },
  Xueyi: {
    icon: require("../../images/character_icon/xueyi_icon.webp"),
    imageSplash: require("../../images/character_splash/xueyi_splash.webp"),
    imageFull: require("../../images/character_full/xueyi_full.webp"),
    fade: require("../../images/character_fade/xueyi_fade.webp"),
  },
  Argenti: {
    icon: require("../../images/character_icon/argenti_icon.webp"),
    imageSplash: require("../../images/character_splash/argenti_splash.webp"),
    imageFull: require("../../images/character_full/argenti_full.webp"),
    fade: require("../../images/character_fade/argenti_fade.webp"),
  },
  Huohuo: {
    icon: require("../../images/character_icon/huohuo_icon.webp"),
    imageSplash: require("../../images/character_splash/huohuo_splash.webp"),
    imageFull: require("../../images/character_full/huohuo_full.webp"),
    fade: require("../../images/character_fade/huohuo_fade.webp"),
  },
  "Dan Heng • Imbibitor Lunae": {
    icon: require("../../images/character_icon/dan_heng_il_icon.webp"),
    imageSplash: require("../../images/character_splash/dan_heng_il_splash.webp"),
    imageFull: require("../../images/character_full/dan_heng_il_full.webp"),
    fade: require("../../images/character_fade/dan_heng_il_fade.webp"),
  },
  Jingliu: {
    icon: require("../../images/character_icon/jingliu_icon.webp"),
    imageSplash: require("../../images/character_splash/jingliu_splash.webp"),
    imageFull: require("../../images/character_full/jingliu_full.webp"),
    fade: require("../../images/character_fade/jingliu_fade.webp"),
  },
  Bailu: {
    icon: require("../../images/character_icon/bailu_icon.webp"),
    imageSplash: require("../../images/character_splash/bailu_splash.webp"),
    imageFull: require("../../images/character_full/bailu_full.webp"),
    fade: require("../../images/character_fade/bailu_fade.webp"),
  },
  Yanqing: {
    icon: require("../../images/character_icon/yanqing_icon.webp"),
    imageSplash: require("../../images/character_splash/yanqing_splash.webp"),
    imageFull: require("../../images/character_full/yanqing_full.webp"),
    fade: require("../../images/character_fade/yanqing_fade.webp"),
  },
  "Fu Xuan": {
    icon: require("../../images/character_icon/fu_xuan_icon.webp"),
    imageSplash: require("../../images/character_splash/fu_xuan_splash.webp"),
    imageFull: require("../../images/character_full/fu_xuan_full.webp"),
    fade: require("../../images/character_fade/fu_xuan_fade.webp"),
  },
  Blade: {
    icon: require("../../images/character_icon/blade_icon.webp"),
    imageSplash: require("../../images/character_splash/blade_splash.webp"),
    imageFull: require("../../images/character_full/blade_full.webp"),
    fade: require("../../images/character_fade/blade_fade.webp"),
  },
  "Jing Yuan": {
    icon: require("../../images/character_icon/jing_yuan_icon.webp"),
    imageSplash: require("../../images/character_splash/jing_yuan_splash.webp"),
    imageFull: require("../../images/character_full/jing_yuan_full.webp"),
    fade: require("../../images/character_fade/jing_yuan_fade.webp"),
  },
  Luocha: {
    icon: require("../../images/character_icon/luocha_icon.webp"),
    imageSplash: require("../../images/character_splash/luocha_splash.webp"),
    imageFull: require("../../images/character_full/luocha_full.webp"),
    fade: require("../../images/character_fade/luocha_fade.webp"),
  },
  "Topaz & Numby": {
    icon: require("../../images/character_icon/topaz_icon.webp"),
    imageSplash: require("../../images/character_splash/topaz_splash.webp"),
    imageFull: require("../../images/character_full/topaz_full.webp"),
    fade: require("../../images/character_fade/topaz_fade.webp"),
  },
  Clara: {
    icon: require("../../images/character_icon/clara_icon.webp"),
    imageSplash: require("../../images/character_splash/clara_splash.webp"),
    imageFull: require("../../images/character_full/clara_full.webp"),
    fade: require("../../images/character_fade/clara_fade.webp"),
  },
  Gepard: {
    icon: require("../../images/character_icon/gepard_icon.webp"),
    imageSplash: require("../../images/character_splash/gepard_splash.webp"),
    imageFull: require("../../images/character_full/gepard_full.webp"),
    fade: require("../../images/character_fade/gepard_fade.webp"),
  },
  Seele: {
    icon: require("../../images/character_icon/seele_icon.webp"),
    imageSplash: require("../../images/character_splash/seele_splash.webp"),
    imageFull: require("../../images/character_full/seele_full.webp"),
    fade: require("../../images/character_fade/seele_fade.webp"),
  },
  Bronya: {
    icon: require("../../images/character_icon/bronya_icon.webp"),
    imageSplash: require("../../images/character_splash/bronya_splash.webp"),
    imageFull: require("../../images/character_full/bronya_full.webp"),
    fade: require("../../images/character_fade/bronya_fade.webp"),
  },
  "Silver Wolf": {
    icon: require("../../images/character_icon/silver_wolf_icon.webp"),
    imageSplash: require("../../images/character_splash/silver_wolf_splash.webp"),
    imageFull: require("../../images/character_full/silver_wolf_full.webp"),
    fade: require("../../images/character_fade/silver_wolf_fade.webp"),
  },
  Kafka: {
    icon: require("../../images/character_icon/kafka_icon.webp"),
    imageSplash: require("../../images/character_splash/kafka_splash.webp"),
    imageFull: require("../../images/character_full/kafka_full.webp"),
    fade: require("../../images/character_fade/kafka_fade.webp"),
  },
  Welt: {
    icon: require("../../images/character_icon/welt_icon.webp"),
    imageSplash: require("../../images/character_splash/welt_splash.webp"),
    imageFull: require("../../images/character_full/welt_full.webp"),
    fade: require("../../images/character_fade/welt_fade.webp"),
  },
  Himeko: {
    icon: require("../../images/character_icon/himeko_icon.webp"),
    imageSplash: require("../../images/character_splash/himeko_splash.webp"),
    imageFull: require("../../images/character_full/himeko_full.webp"),
    fade: require("../../images/character_fade/himeko_fade.webp"),
  },
  Hanya: {
    icon: require("../../images/character_icon/hanya_icon.webp"),
    imageSplash: require("../../images/character_splash/hanya_splash.webp"),
    imageFull: require("../../images/character_full/hanya_full.webp"),
    fade: require("../../images/character_fade/hanya_fade.webp"),
  },
  Guinaifen: {
    icon: require("../../images/character_icon/guinaifen_icon.webp"),
    imageSplash: require("../../images/character_splash/guinaifen_splash.webp"),
    imageFull: require("../../images/character_full/guinaifen_full.webp"),
    fade: require("../../images/character_fade/guinaifen_fade.webp"),
  },
  Yukong: {
    icon: require("../../images/character_icon/yukong_icon.webp"),
    imageSplash: require("../../images/character_splash/yukong_splash.webp"),
    imageFull: require("../../images/character_full/yukong_full.webp"),
    fade: require("../../images/character_fade/yukong_fade.webp"),
  },
  Sushang: {
    icon: require("../../images/character_icon/sushang_icon.webp"),
    imageSplash: require("../../images/character_splash/sushang_splash.webp"),
    imageFull: require("../../images/character_full/sushang_full.webp"),
    fade: require("../../images/character_fade/sushang_fade.webp"),
  },
  Tingyun: {
    icon: require("../../images/character_icon/tingyun_icon.webp"),
    imageSplash: require("../../images/character_splash/tingyun_splash.webp"),
    imageFull: require("../../images/character_full/tingyun_full.webp"),
    fade: require("../../images/character_fade/tingyun_fade.webp"),
  },
  Qingque: {
    icon: require("../../images/character_icon/qingque_icon.webp"),
    imageSplash: require("../../images/character_splash/qingque_splash.webp"),
    imageFull: require("../../images/character_full/qingque_full.webp"),
    fade: require("../../images/character_fade/qingque_fade.webp"),
  },
  Luka: {
    icon: require("../../images/character_icon/luka_icon.webp"),
    imageSplash: require("../../images/character_splash/luka_splash.webp"),
    imageFull: require("../../images/character_full/luka_full.webp"),
    fade: require("../../images/character_fade/luka_fade.webp"),
  },
  Lynx: {
    icon: require("../../images/character_icon/lynx_icon.webp"),
    imageSplash: require("../../images/character_splash/lynx_splash.webp"),
    imageFull: require("../../images/character_full/lynx_full.webp"),
    fade: require("../../images/character_fade/lynx_fade.webp"),
  },
  Hook: {
    icon: require("../../images/character_icon/hook_icon.webp"),
    imageSplash: require("../../images/character_splash/hook_splash.webp"),
    imageFull: require("../../images/character_full/hook_full.webp"),
    fade: require("../../images/character_fade/hook_fade.webp"),
  },
  Sampo: {
    icon: require("../../images/character_icon/sampo_icon.webp"),
    imageSplash: require("../../images/character_splash/sampo_splash.webp"),
    imageFull: require("../../images/character_full/sampo_full.webp"),
    fade: require("../../images/character_fade/sampo_fade.webp"),
  },
  Pela: {
    icon: require("../../images/character_icon/pela_icon.webp"),
    imageSplash: require("../../images/character_splash/pela_splash.webp"),
    imageFull: require("../../images/character_full/pela_full.webp"),
    fade: require("../../images/character_fade/pela_fade.webp"),
  },
  Natasha: {
    icon: require("../../images/character_icon/natasha_icon.webp"),
    imageSplash: require("../../images/character_splash/natasha_splash.webp"),
    imageFull: require("../../images/character_full/natasha_full.webp"),
    fade: require("../../images/character_fade/natasha_fade.webp"),
  },
  Serval: {
    icon: require("../../images/character_icon/serval_icon.webp"),
    imageSplash: require("../../images/character_splash/serval_splash.webp"),
    imageFull: require("../../images/character_full/serval_full.webp"),
    fade: require("../../images/character_fade/serval_fade.webp"),
  },
  Herta: {
    icon: require("../../images/character_icon/herta_icon.webp"),
    imageSplash: require("../../images/character_splash/herta_splash.webp"),
    imageFull: require("../../images/character_full/herta_full.webp"),
    fade: require("../../images/character_fade/herta_fade.webp"),
  },
  Asta: {
    icon: require("../../images/character_icon/asta_icon.webp"),
    imageSplash: require("../../images/character_splash/asta_splash.webp"),
    imageFull: require("../../images/character_full/asta_full.webp"),
    fade: require("../../images/character_fade/asta_fade.webp"),
  },
  Arlan: {
    icon: require("../../images/character_icon/arlan_icon.webp"),
    imageSplash: require("../../images/character_splash/arlan_splash.webp"),
    imageFull: require("../../images/character_full/arlan_full.webp"),
    fade: require("../../images/character_fade/arlan_fade.webp"),
  },
  "Dan Heng": {
    icon: require("../../images/character_icon/dan_heng_icon.webp"),
    imageSplash: require("../../images/character_splash/dan_heng_splash.webp"),
    imageFull: require("../../images/character_full/dan_heng_full.webp"),
    fade: require("../character_fade/dan_heng_fade.webp"),
  },
  "March 7th": {
    icon: require("../../images/character_icon/march_7th_icon.webp"),
    imageSplash: require("../../images/character_splash/march_7th_splash.webp"),
    imageFull: require("../../images/character_full/march_7th_full.webp"),
    fade: require("../character_fade/march_7th_fade.webp"),
  },
  "Trailblazer Boy (Physical)": {
    icon: require("../../images/character_icon/trailblazer_physical_male_icon.webp"),
    imageSplash: require("../../images/character_splash/trailblazer_physical_male_splash.webp"),
    imageFull: require("../../images/character_full/trailblazer_boy_full.webp"),
    fade: require("../character_fade/trailblazer_physical_male_fade.webp"),
  },
  "Trailblazer Girl (Physical)": {
    icon: require("../../images/character_icon/trailblazer_physical_female_icon.webp"),
    imageSplash: require("../../images/character_splash/trailblazer_physical_female_splash.webp"),
    imageFull: require("../../images/character_full/trailblazer_girl_full.webp"),
    fade: require("../character_fade/trailblazer_physical_female_fade.webp"),
  },
  "Trailblazer Boy (Fire)": {
    icon: require("../../images/character_icon/trailblazer_fire_male_icon.webp"),
    imageSplash: require("../../images/character_splash/trailblazer_fire_male_splash.webp"),
    imageFull: require("../../images/character_full/trailblazer_boy_full.webp"),
    fade: require("../character_fade/trailblazer_fire_male_fade.webp"),
  },
  "Trailblazer Girl (Fire)": {
    icon: require("../../images/character_icon/trailblazer_fire_female_icon.webp"),
    imageSplash: require("../../images/character_splash/trailblazer_fire_female_splash.webp"),
    imageFull: require("../../images/character_full/trailblazer_girl_full.webp"),
    fade: require("../character_fade/trailblazer_fire_female_fade.webp"),
  },
};

export default CharacterImage;
