/**
 * This is the list of Character's main skills, not for the child of root branch.
 * For Trailblazer, there did splitted to Boy1, Boy2, Girl1, Girl2 , etc (if necessery).
 */

const CharacterSoul = {
  Argenti: {
    soul1: require("../../images/character_soul/argenti_soul1.webp"),
    soul2: require("../../images/character_soul/argenti_soul2.webp"),
    soul3: require("../../images/character_soul/argenti_soul3.webp"),
    soul4: require("../../images/character_soul/argenti_soul4.webp"),
    soul5: require("../../images/character_soul/argenti_soul5.webp"),
    soul6: require("../../images/character_soul/argenti_soul6.webp"),
  },
  Huohuo: {
    soul1: require("../../images/character_soul/huohuo_soul1.webp"),
    soul2: require("../../images/character_soul/huohuo_soul2.webp"),
    soul3: require("../../images/character_soul/huohuo_soul3.webp"),
    soul4: require("../../images/character_soul/huohuo_soul4.webp"),
    soul5: require("../../images/character_soul/huohuo_soul5.webp"),
    soul6: require("../../images/character_soul/huohuo_soul6.webp"),
  },
  "Dan Heng • Imbibitor Lunae": {
    soul1: require("../../images/character_soul/dan_heng_il_soul1.webp"),
    soul2: require("../../images/character_soul/dan_heng_il_soul2.webp"),
    soul3: require("../../images/character_soul/dan_heng_il_soul3.webp"),
    soul4: require("../../images/character_soul/dan_heng_il_soul4.webp"),
    soul5: require("../../images/character_soul/dan_heng_il_soul5.webp"),
    soul6: require("../../images/character_soul/dan_heng_il_soul6.webp"),
  },
  Jingliu: {
    soul1: require("../../images/character_soul/jingliu_soul1.webp"),
    soul2: require("../../images/character_soul/jingliu_soul2.webp"),
    soul3: require("../../images/character_soul/jingliu_soul3.webp"),
    soul4: require("../../images/character_soul/jingliu_soul4.webp"),
    soul5: require("../../images/character_soul/jingliu_soul5.webp"),
    soul6: require("../../images/character_soul/jingliu_soul6.webp"),
  },
  Bailu: {
    soul1: require("../../images/character_soul/bailu_soul1.webp"),
    soul2: require("../../images/character_soul/bailu_soul2.webp"),
    soul3: require("../../images/character_soul/bailu_soul3.webp"),
    soul4: require("../../images/character_soul/bailu_soul4.webp"),
    soul5: require("../../images/character_soul/bailu_soul5.webp"),
    soul6: require("../../images/character_soul/bailu_soul6.webp"),
  },
  Yanqing: {
    soul1: require("../../images/character_soul/yanqing_soul1.webp"),
    soul2: require("../../images/character_soul/yanqing_soul2.webp"),
    soul3: require("../../images/character_soul/yanqing_soul3.webp"),
    soul4: require("../../images/character_soul/yanqing_soul4.webp"),
    soul5: require("../../images/character_soul/yanqing_soul5.webp"),
    soul6: require("../../images/character_soul/yanqing_soul6.webp"),
  },
  "Fu Xuan": {
    soul1: require("../../images/character_soul/fu_xuan_soul1.webp"),
    soul2: require("../../images/character_soul/fu_xuan_soul2.webp"),
    soul3: require("../../images/character_soul/fu_xuan_soul3.webp"),
    soul4: require("../../images/character_soul/fu_xuan_soul4.webp"),
    soul5: require("../../images/character_soul/fu_xuan_soul5.webp"),
    soul6: require("../../images/character_soul/fu_xuan_soul6.webp"),
  },
  Blade: {
    soul1: require("../../images/character_soul/blade_soul1.webp"),
    soul2: require("../../images/character_soul/blade_soul2.webp"),
    soul3: require("../../images/character_soul/blade_soul3.webp"),
    soul4: require("../../images/character_soul/blade_soul4.webp"),
    soul5: require("../../images/character_soul/blade_soul5.webp"),
    soul6: require("../../images/character_soul/blade_soul6.webp"),
  },
  "Jing Yuan": {
    soul1: require("../../images/character_soul/jing_yuan_soul1.webp"),
    soul2: require("../../images/character_soul/jing_yuan_soul2.webp"),
    soul3: require("../../images/character_soul/jing_yuan_soul3.webp"),
    soul4: require("../../images/character_soul/jing_yuan_soul4.webp"),
    soul5: require("../../images/character_soul/jing_yuan_soul5.webp"),
    soul6: require("../../images/character_soul/jing_yuan_soul6.webp"),
  },
  Luocha: {
    soul1: require("../../images/character_soul/luocha_soul1.webp"),
    soul2: require("../../images/character_soul/luocha_soul2.webp"),
    soul3: require("../../images/character_soul/luocha_soul3.webp"),
    soul4: require("../../images/character_soul/luocha_soul4.webp"),
    soul5: require("../../images/character_soul/luocha_soul5.webp"),
    soul6: require("../../images/character_soul/luocha_soul6.webp"),
  },
  "Topaz & Numby": {
    soul1: require("../../images/character_soul/topaz_soul1.webp"),
    soul2: require("../../images/character_soul/topaz_soul2.webp"),
    soul3: require("../../images/character_soul/topaz_soul3.webp"),
    soul4: require("../../images/character_soul/topaz_soul4.webp"),
    soul5: require("../../images/character_soul/topaz_soul5.webp"),
    soul6: require("../../images/character_soul/topaz_soul6.webp"),
  },
  Clara: {
    soul1: require("../../images/character_soul/clara_soul1.webp"),
    soul2: require("../../images/character_soul/clara_soul2.webp"),
    soul3: require("../../images/character_soul/clara_soul3.webp"),
    soul4: require("../../images/character_soul/clara_soul4.webp"),
    soul5: require("../../images/character_soul/clara_soul5.webp"),
    soul6: require("../../images/character_soul/clara_soul6.webp"),
  },
  Gepard: {
    soul1: require("../../images/character_soul/gepard_soul1.webp"),
    soul2: require("../../images/character_soul/gepard_soul2.webp"),
    soul3: require("../../images/character_soul/gepard_soul3.webp"),
    soul4: require("../../images/character_soul/gepard_soul4.webp"),
    soul5: require("../../images/character_soul/gepard_soul5.webp"),
    soul6: require("../../images/character_soul/gepard_soul6.webp"),
  },
  Seele: {
    soul1: require("../../images/character_soul/seele_soul1.webp"),
    soul2: require("../../images/character_soul/seele_soul2.webp"),
    soul3: require("../../images/character_soul/seele_soul3.webp"),
    soul4: require("../../images/character_soul/seele_soul4.webp"),
    soul5: require("../../images/character_soul/seele_soul5.webp"),
    soul6: require("../../images/character_soul/seele_soul6.webp"),
  },
  Bronya: {
    soul1: require("../../images/character_soul/bronya_soul1.webp"),
    soul2: require("../../images/character_soul/bronya_soul2.webp"),
    soul3: require("../../images/character_soul/bronya_soul3.webp"),
    soul4: require("../../images/character_soul/bronya_soul4.webp"),
    soul5: require("../../images/character_soul/bronya_soul5.webp"),
    soul6: require("../../images/character_soul/bronya_soul6.webp"),
  },
  "Silver Wolf": {
    soul1: require("../../images/character_soul/silver_wolf_soul1.webp"),
    soul2: require("../../images/character_soul/silver_wolf_soul2.webp"),
    soul3: require("../../images/character_soul/silver_wolf_soul3.webp"),
    soul4: require("../../images/character_soul/silver_wolf_soul4.webp"),
    soul5: require("../../images/character_soul/silver_wolf_soul5.webp"),
    soul6: require("../../images/character_soul/silver_wolf_soul6.webp"),
  },
  Kafka: {
    soul1: require("../../images/character_soul/kafka_soul1.webp"),
    soul2: require("../../images/character_soul/kafka_soul2.webp"),
    soul3: require("../../images/character_soul/kafka_soul3.webp"),
    soul4: require("../../images/character_soul/kafka_soul4.webp"),
    soul5: require("../../images/character_soul/kafka_soul5.webp"),
    soul6: require("../../images/character_soul/kafka_soul6.webp"),
  },
  Welt: {
    soul1: require("../../images/character_soul/welt_soul1.webp"),
    soul2: require("../../images/character_soul/welt_soul2.webp"),
    soul3: require("../../images/character_soul/welt_soul3.webp"),
    soul4: require("../../images/character_soul/welt_soul4.webp"),
    soul5: require("../../images/character_soul/welt_soul5.webp"),
    soul6: require("../../images/character_soul/welt_soul6.webp"),
  },
  Himeko: {
    soul1: require("../../images/character_soul/himeko_soul1.webp"),
    soul2: require("../../images/character_soul/himeko_soul2.webp"),
    soul3: require("../../images/character_soul/himeko_soul3.webp"),
    soul4: require("../../images/character_soul/himeko_soul4.webp"),
    soul5: require("../../images/character_soul/himeko_soul5.webp"),
    soul6: require("../../images/character_soul/himeko_soul6.webp"),
  },
  Hanya: {
    soul1: require("../../images/character_soul/hanya_soul1.webp"),
    soul2: require("../../images/character_soul/hanya_soul2.webp"),
    soul3: require("../../images/character_soul/hanya_soul3.webp"),
    soul4: require("../../images/character_soul/hanya_soul4.webp"),
    soul5: require("../../images/character_soul/hanya_soul5.webp"),
    soul6: require("../../images/character_soul/hanya_soul6.webp"),
  },
  Guinaifen: {
    soul1: require("../../images/character_soul/guinaifen_soul1.webp"),
    soul2: require("../../images/character_soul/guinaifen_soul2.webp"),
    soul3: require("../../images/character_soul/guinaifen_soul3.webp"),
    soul4: require("../../images/character_soul/guinaifen_soul4.webp"),
    soul5: require("../../images/character_soul/guinaifen_soul5.webp"),
    soul6: require("../../images/character_soul/guinaifen_soul6.webp"),
  },
  Yukong: {
    soul1: require("../../images/character_soul/yukong_soul1.webp"),
    soul2: require("../../images/character_soul/yukong_soul2.webp"),
    soul3: require("../../images/character_soul/yukong_soul3.webp"),
    soul4: require("../../images/character_soul/yukong_soul4.webp"),
    soul5: require("../../images/character_soul/yukong_soul5.webp"),
    soul6: require("../../images/character_soul/yukong_soul6.webp"),
  },
  Sushang: {
    soul1: require("../../images/character_soul/sushang_soul1.webp"),
    soul2: require("../../images/character_soul/sushang_soul2.webp"),
    soul3: require("../../images/character_soul/sushang_soul3.webp"),
    soul4: require("../../images/character_soul/sushang_soul4.webp"),
    soul5: require("../../images/character_soul/sushang_soul5.webp"),
    soul6: require("../../images/character_soul/sushang_soul6.webp"),
  },
  Tingyun: {
    soul1: require("../../images/character_soul/tingyun_soul1.webp"),
    soul2: require("../../images/character_soul/tingyun_soul2.webp"),
    soul3: require("../../images/character_soul/tingyun_soul3.webp"),
    soul4: require("../../images/character_soul/tingyun_soul4.webp"),
    soul5: require("../../images/character_soul/tingyun_soul5.webp"),
    soul6: require("../../images/character_soul/tingyun_soul6.webp"),
  },
  Qingque: {
    soul1: require("../../images/character_soul/qingque_soul1.webp"),
    soul2: require("../../images/character_soul/qingque_soul2.webp"),
    soul3: require("../../images/character_soul/qingque_soul3.webp"),
    soul4: require("../../images/character_soul/qingque_soul4.webp"),
    soul5: require("../../images/character_soul/qingque_soul5.webp"),
    soul6: require("../../images/character_soul/qingque_soul6.webp"),
  },
  Luka: {
    soul1: require("../../images/character_soul/luka_soul1.webp"),
    soul2: require("../../images/character_soul/luka_soul2.webp"),
    soul3: require("../../images/character_soul/luka_soul3.webp"),
    soul4: require("../../images/character_soul/luka_soul4.webp"),
    soul5: require("../../images/character_soul/luka_soul5.webp"),
    soul6: require("../../images/character_soul/luka_soul6.webp"),
  },
  Lynx: {
    soul1: require("../../images/character_soul/lynx_soul1.webp"),
    soul2: require("../../images/character_soul/lynx_soul2.webp"),
    soul3: require("../../images/character_soul/lynx_soul3.webp"),
    soul4: require("../../images/character_soul/lynx_soul4.webp"),
    soul5: require("../../images/character_soul/lynx_soul5.webp"),
    soul6: require("../../images/character_soul/lynx_soul6.webp"),
  },
  Hook: {
    soul1: require("../../images/character_soul/hook_soul1.webp"),
    soul2: require("../../images/character_soul/hook_soul2.webp"),
    soul3: require("../../images/character_soul/hook_soul3.webp"),
    soul4: require("../../images/character_soul/hook_soul4.webp"),
    soul5: require("../../images/character_soul/hook_soul5.webp"),
    soul6: require("../../images/character_soul/hook_soul6.webp"),
  },
  Sampo: {
    soul1: require("../../images/character_soul/sampo_soul1.webp"),
    soul2: require("../../images/character_soul/sampo_soul2.webp"),
    soul3: require("../../images/character_soul/sampo_soul3.webp"),
    soul4: require("../../images/character_soul/sampo_soul4.webp"),
    soul5: require("../../images/character_soul/sampo_soul5.webp"),
    soul6: require("../../images/character_soul/sampo_soul6.webp"),
  },
  Pela: {
    soul1: require("../../images/character_soul/pela_soul1.webp"),
    soul2: require("../../images/character_soul/pela_soul2.webp"),
    soul3: require("../../images/character_soul/pela_soul3.webp"),
    soul4: require("../../images/character_soul/pela_soul4.webp"),
    soul5: require("../../images/character_soul/pela_soul5.webp"),
    soul6: require("../../images/character_soul/pela_soul6.webp"),
  },
  Natasha: {
    soul1: require("../../images/character_soul/natasha_soul1.webp"),
    soul2: require("../../images/character_soul/natasha_soul2.webp"),
    soul3: require("../../images/character_soul/natasha_soul3.webp"),
    soul4: require("../../images/character_soul/natasha_soul4.webp"),
    soul5: require("../../images/character_soul/natasha_soul5.webp"),
    soul6: require("../../images/character_soul/natasha_soul6.webp"),
  },
  Serval: {
    soul1: require("../../images/character_soul/serval_soul1.webp"),
    soul2: require("../../images/character_soul/serval_soul2.webp"),
    soul3: require("../../images/character_soul/serval_soul3.webp"),
    soul4: require("../../images/character_soul/serval_soul4.webp"),
    soul5: require("../../images/character_soul/serval_soul5.webp"),
    soul6: require("../../images/character_soul/serval_soul6.webp"),
  },
  Herta: {
    soul1: require("../../images/character_soul/herta_soul1.webp"),
    soul2: require("../../images/character_soul/herta_soul2.webp"),
    soul3: require("../../images/character_soul/herta_soul3.webp"),
    soul4: require("../../images/character_soul/herta_soul4.webp"),
    soul5: require("../../images/character_soul/herta_soul5.webp"),
    soul6: require("../../images/character_soul/herta_soul6.webp"),
  },
  Asta: {
    soul1: require("../../images/character_soul/asta_soul1.webp"),
    soul2: require("../../images/character_soul/asta_soul2.webp"),
    soul3: require("../../images/character_soul/asta_soul3.webp"),
    soul4: require("../../images/character_soul/asta_soul4.webp"),
    soul5: require("../../images/character_soul/asta_soul5.webp"),
    soul6: require("../../images/character_soul/asta_soul6.webp"),
  },
  Arlan: {
    soul1: require("../../images/character_soul/arlan_soul1.webp"),
    soul2: require("../../images/character_soul/arlan_soul2.webp"),
    soul3: require("../../images/character_soul/arlan_soul3.webp"),
    soul4: require("../../images/character_soul/arlan_soul4.webp"),
    soul5: require("../../images/character_soul/arlan_soul5.webp"),
    soul6: require("../../images/character_soul/arlan_soul6.webp"),
  },
  "Dan Heng": {
    soul1: require("../../images/character_soul/dan_heng_soul1.webp"),
    soul2: require("../../images/character_soul/dan_heng_soul2.webp"),
    soul3: require("../../images/character_soul/dan_heng_soul3.webp"),
    soul4: require("../../images/character_soul/dan_heng_soul4.webp"),
    soul5: require("../../images/character_soul/dan_heng_soul5.webp"),
    soul6: require("../../images/character_soul/dan_heng_soul6.webp"),
  },
  "March 7th": {
    soul1: require("../../images/character_soul/march_7th_soul1.webp"),
    soul2: require("../../images/character_soul/march_7th_soul2.webp"),
    soul3: require("../../images/character_soul/march_7th_soul3.webp"),
    soul4: require("../../images/character_soul/march_7th_soul4.webp"),
    soul5: require("../../images/character_soul/march_7th_soul5.webp"),
    soul6: require("../../images/character_soul/march_7th_soul6.webp"),
  },
};

export default CharacterSoul;