/**
 * This is the list of Character's main skills, not for the child of root branch.
 * For Trailblazer, there did splitted to Boy1, Boy2, Girl1, Girl2 , etc (if necessery).
 */

const CharacterSoul: any = {
  //add in 2.1.0
  "Acheron": {
    eidolon1: require("../../images/character_eidolon/acheron_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/acheron_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/acheron_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/acheron_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/acheron_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/acheron_eidolon6.webp"),
    soul1: require("../../images/character_soul/acheron_soul1.webp"),
    soul2: require("../../images/character_soul/acheron_soul2.webp"),
    soul3: require("../../images/character_soul/acheron_soul3.webp"),
    soul4: require("../../images/character_soul/acheron_soul4.webp"),
    soul5: require("../../images/character_soul/acheron_soul5.webp"),
    soul6: require("../../images/character_soul/acheron_soul6.webp"),
  },
  "Aventurine": {
    eidolon1: require("../../images/character_eidolon/aventurine_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/aventurine_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/aventurine_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/aventurine_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/aventurine_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/aventurine_eidolon6.webp"),
    soul1: require("../../images/character_soul/aventurine_soul1.webp"),
    soul2: require("../../images/character_soul/aventurine_soul2.webp"),
    soul3: require("../../images/character_soul/aventurine_soul3.webp"),
    soul4: require("../../images/character_soul/aventurine_soul4.webp"),
    soul5: require("../../images/character_soul/aventurine_soul5.webp"),
    soul6: require("../../images/character_soul/aventurine_soul6.webp"),
  },
  "Gallagher": {
    eidolon1: require("../../images/character_eidolon/gallagher_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/gallagher_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/gallagher_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/gallagher_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/gallagher_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/gallagher_eidolon6.webp"),
    soul1: require("../../images/character_soul/gallagher_soul1.webp"),
    soul2: require("../../images/character_soul/gallagher_soul2.webp"),
    soul3: require("../../images/character_soul/gallagher_soul3.webp"),
    soul4: require("../../images/character_soul/gallagher_soul4.webp"),
    soul5: require("../../images/character_soul/gallagher_soul5.webp"),
    soul6: require("../../images/character_soul/gallagher_soul6.webp"),
  },
  //add in 2.0.0
  "Black Swan": {
    eidolon1: require("../../images/character_eidolon/black_swan_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/black_swan_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/black_swan_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/black_swan_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/black_swan_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/black_swan_eidolon6.webp"),
    soul1: require("../../images/character_soul/black_swan_soul1.webp"),
    soul2: require("../../images/character_soul/black_swan_soul2.webp"),
    soul3: require("../../images/character_soul/black_swan_soul3.webp"),
    soul4: require("../../images/character_soul/black_swan_soul4.webp"),
    soul5: require("../../images/character_soul/black_swan_soul5.webp"),
    soul6: require("../../images/character_soul/black_swan_soul6.webp"),
  },
  "Misha": {
    eidolon1: require("../../images/character_eidolon/misha_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/misha_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/misha_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/misha_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/misha_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/misha_eidolon6.webp"),
    soul1: require("../../images/character_soul/misha_soul1.webp"),
    soul2: require("../../images/character_soul/misha_soul2.webp"),
    soul3: require("../../images/character_soul/misha_soul3.webp"),
    soul4: require("../../images/character_soul/misha_soul4.webp"),
    soul5: require("../../images/character_soul/misha_soul5.webp"),
    soul6: require("../../images/character_soul/misha_soul6.webp"),
  },
  "Sparkle": {
    eidolon1: require("../../images/character_eidolon/sparkle_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/sparkle_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/sparkle_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/sparkle_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/sparkle_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/sparkle_eidolon6.webp"),
    soul1: require("../../images/character_soul/sparkle_soul1.webp"),
    soul2: require("../../images/character_soul/sparkle_soul2.webp"),
    soul3: require("../../images/character_soul/sparkle_soul3.webp"),
    soul4: require("../../images/character_soul/sparkle_soul4.webp"),
    soul5: require("../../images/character_soul/sparkle_soul5.webp"),
    soul6: require("../../images/character_soul/sparkle_soul6.webp"),
  },
  //add in 1.6.0
  "Dr. Ratio": {
    eidolon1: require("../../images/character_eidolon/dr_ratio_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/dr_ratio_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/dr_ratio_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/dr_ratio_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/dr_ratio_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/dr_ratio_eidolon6.webp"),
    soul1: require("../../images/character_soul/dr_ratio_soul1.webp"),
    soul2: require("../../images/character_soul/dr_ratio_soul2.webp"),
    soul3: require("../../images/character_soul/dr_ratio_soul3.webp"),
    soul4: require("../../images/character_soul/dr_ratio_soul4.webp"),
    soul5: require("../../images/character_soul/dr_ratio_soul5.webp"),
    soul6: require("../../images/character_soul/dr_ratio_soul6.webp"),
  },
  "Ruan Mei": {
    eidolon1: require("../../images/character_eidolon/ruan_mei_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/ruan_mei_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/ruan_mei_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/ruan_mei_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/ruan_mei_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/ruan_mei_eidolon6.webp"),
    soul1: require("../../images/character_soul/ruan_mei_soul1.webp"),
    soul2: require("../../images/character_soul/ruan_mei_soul2.webp"),
    soul3: require("../../images/character_soul/ruan_mei_soul3.webp"),
    soul4: require("../../images/character_soul/ruan_mei_soul4.webp"),
    soul5: require("../../images/character_soul/ruan_mei_soul5.webp"),
    soul6: require("../../images/character_soul/ruan_mei_soul6.webp"),
  },
  Xueyi: {
    eidolon1: require("../../images/character_eidolon/xueyi_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/xueyi_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/xueyi_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/xueyi_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/xueyi_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/xueyi_eidolon6.webp"),
    soul1: require("../../images/character_soul/xueyi_soul1.webp"),
    soul2: require("../../images/character_soul/xueyi_soul2.webp"),
    soul3: require("../../images/character_soul/xueyi_soul3.webp"),
    soul4: require("../../images/character_soul/xueyi_soul4.webp"),
    soul5: require("../../images/character_soul/xueyi_soul5.webp"),
    soul6: require("../../images/character_soul/xueyi_soul6.webp"),
  },

  Argenti: {
    eidolon1: require("../../images/character_eidolon/argenti_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/argenti_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/argenti_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/argenti_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/argenti_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/argenti_eidolon6.webp"),
    soul1: require("../../images/character_soul/argenti_soul1.webp"),
    soul2: require("../../images/character_soul/argenti_soul2.webp"),
    soul3: require("../../images/character_soul/argenti_soul3.webp"),
    soul4: require("../../images/character_soul/argenti_soul4.webp"),
    soul5: require("../../images/character_soul/argenti_soul5.webp"),
    soul6: require("../../images/character_soul/argenti_soul6.webp"),
  },
  Huohuo: {
    eidolon1: require("../../images/character_eidolon/huohuo_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/huohuo_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/huohuo_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/huohuo_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/huohuo_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/huohuo_eidolon6.webp"),
    soul1: require("../../images/character_soul/huohuo_soul1.webp"),
    soul2: require("../../images/character_soul/huohuo_soul2.webp"),
    soul3: require("../../images/character_soul/huohuo_soul3.webp"),
    soul4: require("../../images/character_soul/huohuo_soul4.webp"),
    soul5: require("../../images/character_soul/huohuo_soul5.webp"),
    soul6: require("../../images/character_soul/huohuo_soul6.webp"),
  },
  "Dan Heng • Imbibitor Lunae": {
    eidolon1: require("../../images/character_eidolon/dan_heng_il_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/dan_heng_il_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/dan_heng_il_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/dan_heng_il_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/dan_heng_il_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/dan_heng_il_eidolon6.webp"),
    soul1: require("../../images/character_soul/dan_heng_il_soul1.webp"),
    soul2: require("../../images/character_soul/dan_heng_il_soul2.webp"),
    soul3: require("../../images/character_soul/dan_heng_il_soul3.webp"),
    soul4: require("../../images/character_soul/dan_heng_il_soul4.webp"),
    soul5: require("../../images/character_soul/dan_heng_il_soul5.webp"),
    soul6: require("../../images/character_soul/dan_heng_il_soul6.webp"),
  },
  Jingliu: {
    eidolon1: require("../../images/character_eidolon/jingliu_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/jingliu_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/jingliu_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/jingliu_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/jingliu_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/jingliu_eidolon6.webp"),
    soul1: require("../../images/character_soul/jingliu_soul1.webp"),
    soul2: require("../../images/character_soul/jingliu_soul2.webp"),
    soul3: require("../../images/character_soul/jingliu_soul3.webp"),
    soul4: require("../../images/character_soul/jingliu_soul4.webp"),
    soul5: require("../../images/character_soul/jingliu_soul5.webp"),
    soul6: require("../../images/character_soul/jingliu_soul6.webp"),
  },
  Bailu: {
    eidolon1: require("../../images/character_eidolon/bailu_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/bailu_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/bailu_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/bailu_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/bailu_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/bailu_eidolon6.webp"),
    soul1: require("../../images/character_soul/bailu_soul1.webp"),
    soul2: require("../../images/character_soul/bailu_soul2.webp"),
    soul3: require("../../images/character_soul/bailu_soul3.webp"),
    soul4: require("../../images/character_soul/bailu_soul4.webp"),
    soul5: require("../../images/character_soul/bailu_soul5.webp"),
    soul6: require("../../images/character_soul/bailu_soul6.webp"),
  },
  Yanqing: {
    eidolon1: require("../../images/character_eidolon/yanqing_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/yanqing_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/yanqing_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/yanqing_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/yanqing_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/yanqing_eidolon6.webp"),
    soul1: require("../../images/character_soul/yanqing_soul1.webp"),
    soul2: require("../../images/character_soul/yanqing_soul2.webp"),
    soul3: require("../../images/character_soul/yanqing_soul3.webp"),
    soul4: require("../../images/character_soul/yanqing_soul4.webp"),
    soul5: require("../../images/character_soul/yanqing_soul5.webp"),
    soul6: require("../../images/character_soul/yanqing_soul6.webp"),
  },
  "Fu Xuan": {
    eidolon1: require("../../images/character_eidolon/fu_xuan_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/fu_xuan_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/fu_xuan_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/fu_xuan_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/fu_xuan_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/fu_xuan_eidolon6.webp"),
    soul1: require("../../images/character_soul/fu_xuan_soul1.webp"),
    soul2: require("../../images/character_soul/fu_xuan_soul2.webp"),
    soul3: require("../../images/character_soul/fu_xuan_soul3.webp"),
    soul4: require("../../images/character_soul/fu_xuan_soul4.webp"),
    soul5: require("../../images/character_soul/fu_xuan_soul5.webp"),
    soul6: require("../../images/character_soul/fu_xuan_soul6.webp"),
  },
  Blade: {
    eidolon1: require("../../images/character_eidolon/blade_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/blade_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/blade_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/blade_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/blade_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/blade_eidolon6.webp"),
    soul1: require("../../images/character_soul/blade_soul1.webp"),
    soul2: require("../../images/character_soul/blade_soul2.webp"),
    soul3: require("../../images/character_soul/blade_soul3.webp"),
    soul4: require("../../images/character_soul/blade_soul4.webp"),
    soul5: require("../../images/character_soul/blade_soul5.webp"),
    soul6: require("../../images/character_soul/blade_soul6.webp"),
  },
  "Jing Yuan": {
    eidolon1: require("../../images/character_eidolon/jing_yuan_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/jing_yuan_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/jing_yuan_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/jing_yuan_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/jing_yuan_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/jing_yuan_eidolon6.webp"),
    soul1: require("../../images/character_soul/jing_yuan_soul1.webp"),
    soul2: require("../../images/character_soul/jing_yuan_soul2.webp"),
    soul3: require("../../images/character_soul/jing_yuan_soul3.webp"),
    soul4: require("../../images/character_soul/jing_yuan_soul4.webp"),
    soul5: require("../../images/character_soul/jing_yuan_soul5.webp"),
    soul6: require("../../images/character_soul/jing_yuan_soul6.webp"),
  },
  Luocha: {
    eidolon1: require("../../images/character_eidolon/luocha_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/luocha_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/luocha_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/luocha_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/luocha_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/luocha_eidolon6.webp"),
    soul1: require("../../images/character_soul/luocha_soul1.webp"),
    soul2: require("../../images/character_soul/luocha_soul2.webp"),
    soul3: require("../../images/character_soul/luocha_soul3.webp"),
    soul4: require("../../images/character_soul/luocha_soul4.webp"),
    soul5: require("../../images/character_soul/luocha_soul5.webp"),
    soul6: require("../../images/character_soul/luocha_soul6.webp"),
  },
  "Topaz & Numby": {
    eidolon1: require("../../images/character_eidolon/topaz_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/topaz_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/topaz_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/topaz_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/topaz_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/topaz_eidolon6.webp"),
    soul1: require("../../images/character_soul/topaz_soul1.webp"),
    soul2: require("../../images/character_soul/topaz_soul2.webp"),
    soul3: require("../../images/character_soul/topaz_soul3.webp"),
    soul4: require("../../images/character_soul/topaz_soul4.webp"),
    soul5: require("../../images/character_soul/topaz_soul5.webp"),
    soul6: require("../../images/character_soul/topaz_soul6.webp"),
  },
  Clara: {
    eidolon1: require("../../images/character_eidolon/clara_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/clara_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/clara_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/clara_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/clara_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/clara_eidolon6.webp"),
    soul1: require("../../images/character_soul/clara_soul1.webp"),
    soul2: require("../../images/character_soul/clara_soul2.webp"),
    soul3: require("../../images/character_soul/clara_soul3.webp"),
    soul4: require("../../images/character_soul/clara_soul4.webp"),
    soul5: require("../../images/character_soul/clara_soul5.webp"),
    soul6: require("../../images/character_soul/clara_soul6.webp"),
  },
  Gepard: {
    eidolon1: require("../../images/character_eidolon/gepard_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/gepard_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/gepard_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/gepard_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/gepard_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/gepard_eidolon6.webp"),
    soul1: require("../../images/character_soul/gepard_soul1.webp"),
    soul2: require("../../images/character_soul/gepard_soul2.webp"),
    soul3: require("../../images/character_soul/gepard_soul3.webp"),
    soul4: require("../../images/character_soul/gepard_soul4.webp"),
    soul5: require("../../images/character_soul/gepard_soul5.webp"),
    soul6: require("../../images/character_soul/gepard_soul6.webp"),
  },
  Seele: {
    eidolon1: require("../../images/character_eidolon/seele_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/seele_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/seele_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/seele_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/seele_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/seele_eidolon6.webp"),
    soul1: require("../../images/character_soul/seele_soul1.webp"),
    soul2: require("../../images/character_soul/seele_soul2.webp"),
    soul3: require("../../images/character_soul/seele_soul3.webp"),
    soul4: require("../../images/character_soul/seele_soul4.webp"),
    soul5: require("../../images/character_soul/seele_soul5.webp"),
    soul6: require("../../images/character_soul/seele_soul6.webp"),
  },
  Bronya: {
    eidolon1: require("../../images/character_eidolon/bronya_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/bronya_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/bronya_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/bronya_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/bronya_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/bronya_eidolon6.webp"),
    soul1: require("../../images/character_soul/bronya_soul1.webp"),
    soul2: require("../../images/character_soul/bronya_soul2.webp"),
    soul3: require("../../images/character_soul/bronya_soul3.webp"),
    soul4: require("../../images/character_soul/bronya_soul4.webp"),
    soul5: require("../../images/character_soul/bronya_soul5.webp"),
    soul6: require("../../images/character_soul/bronya_soul6.webp"),
  },
  "Silver Wolf": {
    eidolon1: require("../../images/character_eidolon/silver_wolf_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/silver_wolf_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/silver_wolf_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/silver_wolf_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/silver_wolf_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/silver_wolf_eidolon6.webp"),
    soul1: require("../../images/character_soul/silver_wolf_soul1.webp"),
    soul2: require("../../images/character_soul/silver_wolf_soul2.webp"),
    soul3: require("../../images/character_soul/silver_wolf_soul3.webp"),
    soul4: require("../../images/character_soul/silver_wolf_soul4.webp"),
    soul5: require("../../images/character_soul/silver_wolf_soul5.webp"),
    soul6: require("../../images/character_soul/silver_wolf_soul6.webp"),
  },
  Kafka: {
    eidolon1: require("../../images/character_eidolon/kafka_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/kafka_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/kafka_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/kafka_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/kafka_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/kafka_eidolon6.webp"),
    soul1: require("../../images/character_soul/kafka_soul1.webp"),
    soul2: require("../../images/character_soul/kafka_soul2.webp"),
    soul3: require("../../images/character_soul/kafka_soul3.webp"),
    soul4: require("../../images/character_soul/kafka_soul4.webp"),
    soul5: require("../../images/character_soul/kafka_soul5.webp"),
    soul6: require("../../images/character_soul/kafka_soul6.webp"),
  },
  Welt: {
    eidolon1: require("../../images/character_eidolon/welt_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/welt_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/welt_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/welt_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/welt_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/welt_eidolon6.webp"),
    soul1: require("../../images/character_soul/welt_soul1.webp"),
    soul2: require("../../images/character_soul/welt_soul2.webp"),
    soul3: require("../../images/character_soul/welt_soul3.webp"),
    soul4: require("../../images/character_soul/welt_soul4.webp"),
    soul5: require("../../images/character_soul/welt_soul5.webp"),
    soul6: require("../../images/character_soul/welt_soul6.webp"),
  },
  Himeko: {
    eidolon1: require("../../images/character_eidolon/himeko_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/himeko_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/himeko_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/himeko_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/himeko_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/himeko_eidolon6.webp"),
    soul1: require("../../images/character_soul/himeko_soul1.webp"),
    soul2: require("../../images/character_soul/himeko_soul2.webp"),
    soul3: require("../../images/character_soul/himeko_soul3.webp"),
    soul4: require("../../images/character_soul/himeko_soul4.webp"),
    soul5: require("../../images/character_soul/himeko_soul5.webp"),
    soul6: require("../../images/character_soul/himeko_soul6.webp"),
  },
  Hanya: {
    eidolon1: require("../../images/character_eidolon/hanya_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/hanya_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/hanya_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/hanya_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/hanya_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/hanya_eidolon6.webp"),
    soul1: require("../../images/character_soul/hanya_soul1.webp"),
    soul2: require("../../images/character_soul/hanya_soul2.webp"),
    soul3: require("../../images/character_soul/hanya_soul3.webp"),
    soul4: require("../../images/character_soul/hanya_soul4.webp"),
    soul5: require("../../images/character_soul/hanya_soul5.webp"),
    soul6: require("../../images/character_soul/hanya_soul6.webp"),
  },
  Guinaifen: {
    eidolon1: require("../../images/character_eidolon/guinaifen_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/guinaifen_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/guinaifen_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/guinaifen_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/guinaifen_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/guinaifen_eidolon6.webp"),
    soul1: require("../../images/character_soul/guinaifen_soul1.webp"),
    soul2: require("../../images/character_soul/guinaifen_soul2.webp"),
    soul3: require("../../images/character_soul/guinaifen_soul3.webp"),
    soul4: require("../../images/character_soul/guinaifen_soul4.webp"),
    soul5: require("../../images/character_soul/guinaifen_soul5.webp"),
    soul6: require("../../images/character_soul/guinaifen_soul6.webp"),
  },
  Yukong: {
    eidolon1: require("../../images/character_eidolon/yukong_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/yukong_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/yukong_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/yukong_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/yukong_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/yukong_eidolon6.webp"),
    soul1: require("../../images/character_soul/yukong_soul1.webp"),
    soul2: require("../../images/character_soul/yukong_soul2.webp"),
    soul3: require("../../images/character_soul/yukong_soul3.webp"),
    soul4: require("../../images/character_soul/yukong_soul4.webp"),
    soul5: require("../../images/character_soul/yukong_soul5.webp"),
    soul6: require("../../images/character_soul/yukong_soul6.webp"),
  },
  Sushang: {
    eidolon1: require("../../images/character_eidolon/sushang_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/sushang_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/sushang_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/sushang_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/sushang_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/sushang_eidolon6.webp"),
    soul1: require("../../images/character_soul/sushang_soul1.webp"),
    soul2: require("../../images/character_soul/sushang_soul2.webp"),
    soul3: require("../../images/character_soul/sushang_soul3.webp"),
    soul4: require("../../images/character_soul/sushang_soul4.webp"),
    soul5: require("../../images/character_soul/sushang_soul5.webp"),
    soul6: require("../../images/character_soul/sushang_soul6.webp"),
  },
  Tingyun: {
    eidolon1: require("../../images/character_eidolon/tingyun_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/tingyun_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/tingyun_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/tingyun_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/tingyun_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/tingyun_eidolon6.webp"),
    soul1: require("../../images/character_soul/tingyun_soul1.webp"),
    soul2: require("../../images/character_soul/tingyun_soul2.webp"),
    soul3: require("../../images/character_soul/tingyun_soul3.webp"),
    soul4: require("../../images/character_soul/tingyun_soul4.webp"),
    soul5: require("../../images/character_soul/tingyun_soul5.webp"),
    soul6: require("../../images/character_soul/tingyun_soul6.webp"),
  },
  Qingque: {
    eidolon1: require("../../images/character_eidolon/qingque_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/qingque_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/qingque_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/qingque_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/qingque_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/qingque_eidolon6.webp"),
    soul1: require("../../images/character_soul/qingque_soul1.webp"),
    soul2: require("../../images/character_soul/qingque_soul2.webp"),
    soul3: require("../../images/character_soul/qingque_soul3.webp"),
    soul4: require("../../images/character_soul/qingque_soul4.webp"),
    soul5: require("../../images/character_soul/qingque_soul5.webp"),
    soul6: require("../../images/character_soul/qingque_soul6.webp"),
  },
  Luka: {
    eidolon1: require("../../images/character_eidolon/luka_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/luka_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/luka_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/luka_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/luka_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/luka_eidolon6.webp"),
    soul1: require("../../images/character_soul/luka_soul1.webp"),
    soul2: require("../../images/character_soul/luka_soul2.webp"),
    soul3: require("../../images/character_soul/luka_soul3.webp"),
    soul4: require("../../images/character_soul/luka_soul4.webp"),
    soul5: require("../../images/character_soul/luka_soul5.webp"),
    soul6: require("../../images/character_soul/luka_soul6.webp"),
  },
  Lynx: {
    eidolon1: require("../../images/character_eidolon/lynx_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/lynx_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/lynx_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/lynx_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/lynx_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/lynx_eidolon6.webp"),
    soul1: require("../../images/character_soul/lynx_soul1.webp"),
    soul2: require("../../images/character_soul/lynx_soul2.webp"),
    soul3: require("../../images/character_soul/lynx_soul3.webp"),
    soul4: require("../../images/character_soul/lynx_soul4.webp"),
    soul5: require("../../images/character_soul/lynx_soul5.webp"),
    soul6: require("../../images/character_soul/lynx_soul6.webp"),
  },
  Hook: {
    eidolon1: require("../../images/character_eidolon/hook_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/hook_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/hook_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/hook_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/hook_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/hook_eidolon6.webp"),
    soul1: require("../../images/character_soul/hook_soul1.webp"),
    soul2: require("../../images/character_soul/hook_soul2.webp"),
    soul3: require("../../images/character_soul/hook_soul3.webp"),
    soul4: require("../../images/character_soul/hook_soul4.webp"),
    soul5: require("../../images/character_soul/hook_soul5.webp"),
    soul6: require("../../images/character_soul/hook_soul6.webp"),
  },
  Sampo: {
    eidolon1: require("../../images/character_eidolon/sampo_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/sampo_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/sampo_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/sampo_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/sampo_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/sampo_eidolon6.webp"),
    soul1: require("../../images/character_soul/sampo_soul1.webp"),
    soul2: require("../../images/character_soul/sampo_soul2.webp"),
    soul3: require("../../images/character_soul/sampo_soul3.webp"),
    soul4: require("../../images/character_soul/sampo_soul4.webp"),
    soul5: require("../../images/character_soul/sampo_soul5.webp"),
    soul6: require("../../images/character_soul/sampo_soul6.webp"),
  },
  Pela: {
    eidolon1: require("../../images/character_eidolon/pela_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/pela_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/pela_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/pela_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/pela_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/pela_eidolon6.webp"),
    soul1: require("../../images/character_soul/pela_soul1.webp"),
    soul2: require("../../images/character_soul/pela_soul2.webp"),
    soul3: require("../../images/character_soul/pela_soul3.webp"),
    soul4: require("../../images/character_soul/pela_soul4.webp"),
    soul5: require("../../images/character_soul/pela_soul5.webp"),
    soul6: require("../../images/character_soul/pela_soul6.webp"),
  },
  Natasha: {
    eidolon1: require("../../images/character_eidolon/natasha_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/natasha_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/natasha_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/natasha_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/natasha_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/natasha_eidolon6.webp"),
    soul1: require("../../images/character_soul/natasha_soul1.webp"),
    soul2: require("../../images/character_soul/natasha_soul2.webp"),
    soul3: require("../../images/character_soul/natasha_soul3.webp"),
    soul4: require("../../images/character_soul/natasha_soul4.webp"),
    soul5: require("../../images/character_soul/natasha_soul5.webp"),
    soul6: require("../../images/character_soul/natasha_soul6.webp"),
  },
  Serval: {
    eidolon1: require("../../images/character_eidolon/serval_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/serval_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/serval_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/serval_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/serval_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/serval_eidolon6.webp"),
    soul1: require("../../images/character_soul/serval_soul1.webp"),
    soul2: require("../../images/character_soul/serval_soul2.webp"),
    soul3: require("../../images/character_soul/serval_soul3.webp"),
    soul4: require("../../images/character_soul/serval_soul4.webp"),
    soul5: require("../../images/character_soul/serval_soul5.webp"),
    soul6: require("../../images/character_soul/serval_soul6.webp"),
  },
  Herta: {
    eidolon1: require("../../images/character_eidolon/herta_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/herta_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/herta_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/herta_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/herta_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/herta_eidolon6.webp"),
    soul1: require("../../images/character_soul/herta_soul1.webp"),
    soul2: require("../../images/character_soul/herta_soul2.webp"),
    soul3: require("../../images/character_soul/herta_soul3.webp"),
    soul4: require("../../images/character_soul/herta_soul4.webp"),
    soul5: require("../../images/character_soul/herta_soul5.webp"),
    soul6: require("../../images/character_soul/herta_soul6.webp"),
  },
  Asta: {
    eidolon1: require("../../images/character_eidolon/asta_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/asta_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/asta_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/asta_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/asta_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/asta_eidolon6.webp"),
    soul1: require("../../images/character_soul/asta_soul1.webp"),
    soul2: require("../../images/character_soul/asta_soul2.webp"),
    soul3: require("../../images/character_soul/asta_soul3.webp"),
    soul4: require("../../images/character_soul/asta_soul4.webp"),
    soul5: require("../../images/character_soul/asta_soul5.webp"),
    soul6: require("../../images/character_soul/asta_soul6.webp"),
  },
  Arlan: {
    eidolon1: require("../../images/character_eidolon/arlan_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/arlan_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/arlan_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/arlan_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/arlan_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/arlan_eidolon6.webp"),
    soul1: require("../../images/character_soul/arlan_soul1.webp"),
    soul2: require("../../images/character_soul/arlan_soul2.webp"),
    soul3: require("../../images/character_soul/arlan_soul3.webp"),
    soul4: require("../../images/character_soul/arlan_soul4.webp"),
    soul5: require("../../images/character_soul/arlan_soul5.webp"),
    soul6: require("../../images/character_soul/arlan_soul6.webp"),
  },
  "Dan Heng": {
    eidolon1: require("../../images/character_eidolon/dan_heng_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/dan_heng_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/dan_heng_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/dan_heng_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/dan_heng_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/dan_heng_eidolon6.webp"),
    soul1: require("../../images/character_soul/dan_heng_soul1.webp"),
    soul2: require("../../images/character_soul/dan_heng_soul2.webp"),
    soul3: require("../../images/character_soul/dan_heng_soul3.webp"),
    soul4: require("../../images/character_soul/dan_heng_soul4.webp"),
    soul5: require("../../images/character_soul/dan_heng_soul5.webp"),
    soul6: require("../../images/character_soul/dan_heng_soul6.webp"),
  },
  "March 7th": {
    eidolon1: require("../../images/character_eidolon/march_7th_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/march_7th_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/march_7th_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/march_7th_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/march_7th_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/march_7th_eidolon6.webp"),
    soul1: require("../../images/character_soul/march_7th_soul1.webp"),
    soul2: require("../../images/character_soul/march_7th_soul2.webp"),
    soul3: require("../../images/character_soul/march_7th_soul3.webp"),
    soul4: require("../../images/character_soul/march_7th_soul4.webp"),
    soul5: require("../../images/character_soul/march_7th_soul5.webp"),
    soul6: require("../../images/character_soul/march_7th_soul6.webp"),
  },
  "Trailblazer Boy (Physical)": {
    eidolon1: require("../../images/character_eidolon/trailblazer_male_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/trailblazer_male_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/trailblazer_male_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/trailblazer_male_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/trailblazer_male_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/trailblazer_male_eidolon6.webp"),
    soul1: require("../../images/character_soul/trailblazer_physical_soul1.webp"),
    soul2: require("../../images/character_soul/trailblazer_physical_soul2.webp"),
    soul3: require("../../images/character_soul/trailblazer_physical_soul3.webp"),
    soul4: require("../../images/character_soul/trailblazer_physical_soul4.webp"),
    soul5: require("../../images/character_soul/trailblazer_physical_soul5.webp"),
    soul6: require("../../images/character_soul/trailblazer_physical_soul6.webp"),
  },
  "Trailblazer Girl (Physical)": {
    eidolon1: require("../../images/character_eidolon/trailblazer_female_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/trailblazer_female_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/trailblazer_female_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/trailblazer_female_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/trailblazer_female_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/trailblazer_female_eidolon6.webp"),
    soul1: require("../../images/character_soul/trailblazer_physical_soul1.webp"),
    soul2: require("../../images/character_soul/trailblazer_physical_soul2.webp"),
    soul3: require("../../images/character_soul/trailblazer_physical_soul3.webp"),
    soul4: require("../../images/character_soul/trailblazer_physical_soul4.webp"),
    soul5: require("../../images/character_soul/trailblazer_physical_soul5.webp"),
    soul6: require("../../images/character_soul/trailblazer_physical_soul6.webp"),
  },
  "Trailblazer Boy (Fire)": {
    eidolon1: require("../../images/character_eidolon/trailblazer_male_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/trailblazer_male_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/trailblazer_male_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/trailblazer_male_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/trailblazer_male_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/trailblazer_male_eidolon6.webp"),
    soul1: require("../../images/character_soul/trailblazer_fire_soul1.webp"),
    soul2: require("../../images/character_soul/trailblazer_fire_soul2.webp"),
    soul3: require("../../images/character_soul/trailblazer_fire_soul3.webp"),
    soul4: require("../../images/character_soul/trailblazer_fire_soul4.webp"),
    soul5: require("../../images/character_soul/trailblazer_fire_soul5.webp"),
    soul6: require("../../images/character_soul/trailblazer_fire_soul6.webp"),
  },
  "Trailblazer Girl (Fire)": {
    eidolon1: require("../../images/character_eidolon/trailblazer_female_eidolon1.webp"),
    eidolon2: require("../../images/character_eidolon/trailblazer_female_eidolon2.webp"),
    eidolon3: require("../../images/character_eidolon/trailblazer_female_eidolon3.webp"),
    eidolon4: require("../../images/character_eidolon/trailblazer_female_eidolon4.webp"),
    eidolon5: require("../../images/character_eidolon/trailblazer_female_eidolon5.webp"),
    eidolon6: require("../../images/character_eidolon/trailblazer_female_eidolon6.webp"),
    soul1: require("../../images/character_soul/trailblazer_fire_soul1.webp"),
    soul2: require("../../images/character_soul/trailblazer_fire_soul2.webp"),
    soul3: require("../../images/character_soul/trailblazer_fire_soul3.webp"),
    soul4: require("../../images/character_soul/trailblazer_fire_soul4.webp"),
    soul5: require("../../images/character_soul/trailblazer_fire_soul5.webp"),
    soul6: require("../../images/character_soul/trailblazer_fire_soul6.webp"),
  },
};
export default CharacterSoul;
