/**
 * This is the list of Character's main skills, not for the child of root branch.
 * For Trailblazer, there did splitted to Boy1, Boy2, Girl1, Girl2 , etc (if necessery).
 */

const CharacterSkillMain: any = {
  //add in 2.1.0
  "Acheron": {
    skill1: require("../../images/character_skill/acheron_skill1.webp"),
    skill2: require("../../images/character_skill/acheron_skill2.webp"),
    skill3: require("../../images/character_skill/acheron_skill3.webp"),
    skill4: require("../../images/character_skill/acheron_skill4.webp"),
    skill6: require("../../images/character_skill/acheron_skill6.webp"),
  },
  "Aventurine": {
    skill1: require("../../images/character_skill/aventurine_skill1.webp"),
    skill2: require("../../images/character_skill/aventurine_skill2.webp"),
    skill3: require("../../images/character_skill/aventurine_skill3.webp"),
    skill4: require("../../images/character_skill/aventurine_skill4.webp"),
    skill6: require("../../images/character_skill/aventurine_skill6.webp"),
  },
  "Gallagher": {
    skill1: require("../../images/character_skill/gallagher_skill1.webp"),
    skill2: require("../../images/character_skill/gallagher_skill2.webp"),
    skill3: require("../../images/character_skill/gallagher_skill3.webp"),
    skill4: require("../../images/character_skill/gallagher_skill4.webp"),
    skill6: require("../../images/character_skill/gallagher_skill6.webp"),
  },
  //add in 2.0.0
  "Black Swan": {
    skill1: require("../../images/character_skill/black_swan_skill1.webp"),
    skill2: require("../../images/character_skill/black_swan_skill2.webp"),
    skill3: require("../../images/character_skill/black_swan_skill3.webp"),
    skill4: require("../../images/character_skill/black_swan_skill4.webp"),
    skill6: require("../../images/character_skill/black_swan_skill6.webp"),
  },
  "Misha": {
    skill1: require("../../images/character_skill/misha_skill1.webp"),
    skill2: require("../../images/character_skill/misha_skill2.webp"),
    skill3: require("../../images/character_skill/misha_skill3.webp"),
    skill4: require("../../images/character_skill/misha_skill4.webp"),
    skill6: require("../../images/character_skill/misha_skill6.webp"),
  },
  "Sparkle": {
    skill1: require("../../images/character_skill/sparkle_skill1.webp"),
    skill2: require("../../images/character_skill/sparkle_skill2.webp"),
    skill3: require("../../images/character_skill/sparkle_skill3.webp"),
    skill4: require("../../images/character_skill/sparkle_skill4.webp"),
    skill6: require("../../images/character_skill/sparkle_skill6.webp"),
  },
  //add in 1.6.0
  "Dr. Ratio": {
    skill1: require("../../images/character_skill/dr_ratio_skill1.webp"),
    skill2: require("../../images/character_skill/dr_ratio_skill2.webp"),
    skill3: require("../../images/character_skill/dr_ratio_skill3.webp"),
    skill4: require("../../images/character_skill/dr_ratio_skill4.webp"),
    skill6: require("../../images/character_skill/dr_ratio_skill6.webp"),
  },
  "Ruan Mei": {
    skill1: require("../../images/character_skill/ruan_mei_skill1.webp"),
    skill2: require("../../images/character_skill/ruan_mei_skill2.webp"),
    skill3: require("../../images/character_skill/ruan_mei_skill3.webp"),
    skill4: require("../../images/character_skill/ruan_mei_skill4.webp"),
    skill6: require("../../images/character_skill/ruan_mei_skill6.webp"),
  },
  Xueyi: {
    skill1: require("../../images/character_skill/xueyi_skill1.webp"),
    skill2: require("../../images/character_skill/xueyi_skill2.webp"),
    skill3: require("../../images/character_skill/xueyi_skill3.webp"),
    skill4: require("../../images/character_skill/xueyi_skill4.webp"),
    skill6: require("../../images/character_skill/xueyi_skill6.webp"),
  },

  Argenti: {
    skill1: require("../../images/character_skill/argenti_skill1.webp"),
    skill2: require("../../images/character_skill/argenti_skill2.webp"),
    skill3: require("../../images/character_skill/argenti_skill3.webp"),
    skill4: require("../../images/character_skill/argenti_skill4.webp"),
    skill6: require("../../images/character_skill/argenti_skill6.webp"),
  },
  Huohuo: {
    skill1: require("../../images/character_skill/huohuo_skill1.webp"),
    skill2: require("../../images/character_skill/huohuo_skill2.webp"),
    skill3: require("../../images/character_skill/huohuo_skill3.webp"),
    skill4: require("../../images/character_skill/huohuo_skill4.webp"),
    skill6: require("../../images/character_skill/huohuo_skill6.webp"),
  },
  "Dan Heng • Imbibitor Lunae": {
    skill1: require("../../images/character_skill/dan_heng_il_skill1.webp"),
    skill2: require("../../images/character_skill/dan_heng_il_skill2.webp"),
    skill3: require("../../images/character_skill/dan_heng_il_skill3.webp"),
    skill4: require("../../images/character_skill/dan_heng_il_skill4.webp"),
    skill6: require("../../images/character_skill/dan_heng_il_skill6.webp"),
  },
  Jingliu: {
    skill1: require("../../images/character_skill/jingliu_skill1.webp"),
    skill2: require("../../images/character_skill/jingliu_skill2.webp"),
    skill3: require("../../images/character_skill/jingliu_skill3.webp"),
    skill4: require("../../images/character_skill/jingliu_skill4.webp"),
    skill6: require("../../images/character_skill/jingliu_skill6.webp"),
  },
  Bailu: {
    skill1: require("../../images/character_skill/bailu_skill1.webp"),
    skill2: require("../../images/character_skill/bailu_skill2.webp"),
    skill3: require("../../images/character_skill/bailu_skill3.webp"),
    skill4: require("../../images/character_skill/bailu_skill4.webp"),
    skill6: require("../../images/character_skill/bailu_skill6.webp"),
  },
  Yanqing: {
    skill1: require("../../images/character_skill/yanqing_skill1.webp"),
    skill2: require("../../images/character_skill/yanqing_skill2.webp"),
    skill3: require("../../images/character_skill/yanqing_skill3.webp"),
    skill4: require("../../images/character_skill/yanqing_skill4.webp"),
    skill6: require("../../images/character_skill/yanqing_skill6.webp"),
  },
  "Fu Xuan": {
    skill1: require("../../images/character_skill/fu_xuan_skill1.webp"),
    skill2: require("../../images/character_skill/fu_xuan_skill2.webp"),
    skill3: require("../../images/character_skill/fu_xuan_skill3.webp"),
    skill4: require("../../images/character_skill/fu_xuan_skill4.webp"),
    skill6: require("../../images/character_skill/fu_xuan_skill6.webp"),
  },
  Blade: {
    skill1: require("../../images/character_skill/blade_skill1.webp"),
    skill2: require("../../images/character_skill/blade_skill2.webp"),
    skill3: require("../../images/character_skill/blade_skill3.webp"),
    skill4: require("../../images/character_skill/blade_skill4.webp"),
    skill6: require("../../images/character_skill/blade_skill6.webp"),
  },
  "Jing Yuan": {
    skill1: require("../../images/character_skill/jing_yuan_skill1.webp"),
    skill2: require("../../images/character_skill/jing_yuan_skill2.webp"),
    skill3: require("../../images/character_skill/jing_yuan_skill3.webp"),
    skill4: require("../../images/character_skill/jing_yuan_skill4.webp"),
    skill6: require("../../images/character_skill/jing_yuan_skill6.webp"),
  },
  Luocha: {
    skill1: require("../../images/character_skill/luocha_skill1.webp"),
    skill2: require("../../images/character_skill/luocha_skill2.webp"),
    skill3: require("../../images/character_skill/luocha_skill3.webp"),
    skill4: require("../../images/character_skill/luocha_skill4.webp"),
    skill6: require("../../images/character_skill/luocha_skill6.webp"),
  },
  "Topaz & Numby": {
    skill1: require("../../images/character_skill/topaz_skill1.webp"),
    skill2: require("../../images/character_skill/topaz_skill2.webp"),
    skill3: require("../../images/character_skill/topaz_skill3.webp"),
    skill4: require("../../images/character_skill/topaz_skill4.webp"),
    skill6: require("../../images/character_skill/topaz_skill6.webp"),
  },
  Clara: {
    skill1: require("../../images/character_skill/clara_skill1.webp"),
    skill2: require("../../images/character_skill/clara_skill2.webp"),
    skill3: require("../../images/character_skill/clara_skill3.webp"),
    skill4: require("../../images/character_skill/clara_skill4.webp"),
    skill6: require("../../images/character_skill/clara_skill6.webp"),
  },
  Gepard: {
    skill1: require("../../images/character_skill/gepard_skill1.webp"),
    skill2: require("../../images/character_skill/gepard_skill2.webp"),
    skill3: require("../../images/character_skill/gepard_skill3.webp"),
    skill4: require("../../images/character_skill/gepard_skill4.webp"),
    skill6: require("../../images/character_skill/gepard_skill6.webp"),
  },
  Seele: {
    skill1: require("../../images/character_skill/seele_skill1.webp"),
    skill2: require("../../images/character_skill/seele_skill2.webp"),
    skill3: require("../../images/character_skill/seele_skill3.webp"),
    skill4: require("../../images/character_skill/seele_skill4.webp"),
    skill6: require("../../images/character_skill/seele_skill6.webp"),
  },
  Bronya: {
    skill1: require("../../images/character_skill/bronya_skill1.webp"),
    skill2: require("../../images/character_skill/bronya_skill2.webp"),
    skill3: require("../../images/character_skill/bronya_skill3.webp"),
    skill4: require("../../images/character_skill/bronya_skill4.webp"),
    skill6: require("../../images/character_skill/bronya_skill6.webp"),
  },
  "Silver Wolf": {
    skill1: require("../../images/character_skill/silver_wolf_skill1.webp"),
    skill2: require("../../images/character_skill/silver_wolf_skill2.webp"),
    skill3: require("../../images/character_skill/silver_wolf_skill3.webp"),
    skill4: require("../../images/character_skill/silver_wolf_skill4.webp"),
    skill6: require("../../images/character_skill/silver_wolf_skill6.webp"),
  },
  Kafka: {
    skill1: require("../../images/character_skill/kafka_skill1.webp"),
    skill2: require("../../images/character_skill/kafka_skill2.webp"),
    skill3: require("../../images/character_skill/kafka_skill3.webp"),
    skill4: require("../../images/character_skill/kafka_skill4.webp"),
    skill6: require("../../images/character_skill/kafka_skill6.webp"),
  },
  Welt: {
    skill1: require("../../images/character_skill/welt_skill1.webp"),
    skill2: require("../../images/character_skill/welt_skill2.webp"),
    skill3: require("../../images/character_skill/welt_skill3.webp"),
    skill4: require("../../images/character_skill/welt_skill4.webp"),
    skill6: require("../../images/character_skill/welt_skill6.webp"),
  },
  Himeko: {
    skill1: require("../../images/character_skill/himeko_skill1.webp"),
    skill2: require("../../images/character_skill/himeko_skill2.webp"),
    skill3: require("../../images/character_skill/himeko_skill3.webp"),
    skill4: require("../../images/character_skill/himeko_skill4.webp"),
    skill6: require("../../images/character_skill/himeko_skill6.webp"),
  },
  Hanya: {
    skill1: require("../../images/character_skill/hanya_skill1.webp"),
    skill2: require("../../images/character_skill/hanya_skill2.webp"),
    skill3: require("../../images/character_skill/hanya_skill3.webp"),
    skill4: require("../../images/character_skill/hanya_skill4.webp"),
    skill6: require("../../images/character_skill/hanya_skill6.webp"),
  },
  Guinaifen: {
    skill1: require("../../images/character_skill/guinaifen_skill1.webp"),
    skill2: require("../../images/character_skill/guinaifen_skill2.webp"),
    skill3: require("../../images/character_skill/guinaifen_skill3.webp"),
    skill4: require("../../images/character_skill/guinaifen_skill4.webp"),
    skill6: require("../../images/character_skill/guinaifen_skill6.webp"),
  },
  Yukong: {
    skill1: require("../../images/character_skill/yukong_skill1.webp"),
    skill2: require("../../images/character_skill/yukong_skill2.webp"),
    skill3: require("../../images/character_skill/yukong_skill3.webp"),
    skill4: require("../../images/character_skill/yukong_skill4.webp"),
    skill6: require("../../images/character_skill/yukong_skill6.webp"),
  },
  Sushang: {
    skill1: require("../../images/character_skill/sushang_skill1.webp"),
    skill2: require("../../images/character_skill/sushang_skill2.webp"),
    skill3: require("../../images/character_skill/sushang_skill3.webp"),
    skill4: require("../../images/character_skill/sushang_skill4.webp"),
    skill6: require("../../images/character_skill/sushang_skill6.webp"),
  },
  Tingyun: {
    skill1: require("../../images/character_skill/tingyun_skill1.webp"),
    skill2: require("../../images/character_skill/tingyun_skill2.webp"),
    skill3: require("../../images/character_skill/tingyun_skill3.webp"),
    skill4: require("../../images/character_skill/tingyun_skill4.webp"),
    skill6: require("../../images/character_skill/tingyun_skill6.webp"),
  },
  Qingque: {
    skill1: require("../../images/character_skill/qingque_skill1.webp"),
    skill2: require("../../images/character_skill/qingque_skill2.webp"),
    skill3: require("../../images/character_skill/qingque_skill3.webp"),
    skill4: require("../../images/character_skill/qingque_skill4.webp"),
    skill6: require("../../images/character_skill/qingque_skill6.webp"),
  },
  Luka: {
    skill1: require("../../images/character_skill/luka_skill1.webp"),
    skill2: require("../../images/character_skill/luka_skill2.webp"),
    skill3: require("../../images/character_skill/luka_skill3.webp"),
    skill4: require("../../images/character_skill/luka_skill4.webp"),
    skill6: require("../../images/character_skill/luka_skill6.webp"),
  },
  Lynx: {
    skill1: require("../../images/character_skill/lynx_skill1.webp"),
    skill2: require("../../images/character_skill/lynx_skill2.webp"),
    skill3: require("../../images/character_skill/lynx_skill3.webp"),
    skill4: require("../../images/character_skill/lynx_skill4.webp"),
    skill6: require("../../images/character_skill/lynx_skill6.webp"),
  },
  Hook: {
    skill1: require("../../images/character_skill/hook_skill1.webp"),
    skill2: require("../../images/character_skill/hook_skill2.webp"),
    skill3: require("../../images/character_skill/hook_skill3.webp"),
    skill4: require("../../images/character_skill/hook_skill4.webp"),
    skill6: require("../../images/character_skill/hook_skill6.webp"),
  },
  Sampo: {
    skill1: require("../../images/character_skill/sampo_skill1.webp"),
    skill2: require("../../images/character_skill/sampo_skill2.webp"),
    skill3: require("../../images/character_skill/sampo_skill3.webp"),
    skill4: require("../../images/character_skill/sampo_skill4.webp"),
    skill6: require("../../images/character_skill/sampo_skill6.webp"),
  },
  Pela: {
    skill1: require("../../images/character_skill/pela_skill1.webp"),
    skill2: require("../../images/character_skill/pela_skill2.webp"),
    skill3: require("../../images/character_skill/pela_skill3.webp"),
    skill4: require("../../images/character_skill/pela_skill4.webp"),
    skill6: require("../../images/character_skill/pela_skill6.webp"),
  },
  Natasha: {
    skill1: require("../../images/character_skill/natasha_skill1.webp"),
    skill2: require("../../images/character_skill/natasha_skill2.webp"),
    skill3: require("../../images/character_skill/natasha_skill3.webp"),
    skill4: require("../../images/character_skill/natasha_skill4.webp"),
    skill6: require("../../images/character_skill/natasha_skill6.webp"),
  },
  Serval: {
    skill1: require("../../images/character_skill/serval_skill1.webp"),
    skill2: require("../../images/character_skill/serval_skill2.webp"),
    skill3: require("../../images/character_skill/serval_skill3.webp"),
    skill4: require("../../images/character_skill/serval_skill4.webp"),
    skill6: require("../../images/character_skill/serval_skill6.webp"),
  },
  Herta: {
    skill1: require("../../images/character_skill/herta_skill1.webp"),
    skill2: require("../../images/character_skill/herta_skill2.webp"),
    skill3: require("../../images/character_skill/herta_skill3.webp"),
    skill4: require("../../images/character_skill/herta_skill4.webp"),
    skill6: require("../../images/character_skill/herta_skill6.webp"),
  },
  Asta: {
    skill1: require("../../images/character_skill/asta_skill1.webp"),
    skill2: require("../../images/character_skill/asta_skill2.webp"),
    skill3: require("../../images/character_skill/asta_skill3.webp"),
    skill4: require("../../images/character_skill/asta_skill4.webp"),
    skill6: require("../../images/character_skill/asta_skill6.webp"),
  },
  Arlan: {
    skill1: require("../../images/character_skill/arlan_skill1.webp"),
    skill2: require("../../images/character_skill/arlan_skill2.webp"),
    skill3: require("../../images/character_skill/arlan_skill3.webp"),
    skill4: require("../../images/character_skill/arlan_skill4.webp"),
    skill6: require("../../images/character_skill/arlan_skill6.webp"),
  },
  "Dan Heng": {
    skill1: require("../../images/character_skill/dan_heng_skill1.webp"),
    skill2: require("../../images/character_skill/dan_heng_skill2.webp"),
    skill3: require("../../images/character_skill/dan_heng_skill3.webp"),
    skill4: require("../../images/character_skill/dan_heng_skill4.webp"),
    skill6: require("../../images/character_skill/dan_heng_skill6.webp"),
  },
  "March 7th": {
    skill1: require("../../images/character_skill/march_7th_skill1.webp"),
    skill2: require("../../images/character_skill/march_7th_skill2.webp"),
    skill3: require("../../images/character_skill/march_7th_skill3.webp"),
    skill4: require("../../images/character_skill/march_7th_skill4.webp"),
    skill6: require("../../images/character_skill/march_7th_skill6.webp"),
  },
  "Trailblazer Boy (Physical)": {
    skill1: require("../../images/character_skill/trailblazer_physical_skill1.webp"),
    skill2: require("../../images/character_skill/trailblazer_physical_skill2.webp"),
    skill3: require("../../images/character_skill/trailblazer_physical_skill3.webp"),
    skill4: require("../../images/character_skill/trailblazer_physical_skill4.webp"),
    skill6: require("../../images/character_skill/trailblazer_physical_skill6.webp"),
  },
  "Trailblazer Girl (Physical)": {
    skill1: require("../../images/character_skill/trailblazer_physical_skill1.webp"),
    skill2: require("../../images/character_skill/trailblazer_physical_skill2.webp"),
    skill3: require("../../images/character_skill/trailblazer_physical_skill3.webp"),
    skill4: require("../../images/character_skill/trailblazer_physical_skill4.webp"),
    skill6: require("../../images/character_skill/trailblazer_physical_skill6.webp"),
  },
  "Trailblazer Boy (Fire)": {
    skill1: require("../../images/character_skill/trailblazer_fire_skill1.webp"),
    skill2: require("../../images/character_skill/trailblazer_fire_skill2.webp"),
    skill3: require("../../images/character_skill/trailblazer_fire_skill3.webp"),
    skill4: require("../../images/character_skill/trailblazer_fire_skill4.webp"),
    skill6: require("../../images/character_skill/trailblazer_fire_skill6.webp"),
  },
  "Trailblazer Girl (Fire)": {
    skill1: require("../../images/character_skill/trailblazer_fire_skill1.webp"),
    skill2: require("../../images/character_skill/trailblazer_fire_skill2.webp"),
    skill3: require("../../images/character_skill/trailblazer_fire_skill3.webp"),
    skill4: require("../../images/character_skill/trailblazer_fire_skill4.webp"),
    skill6: require("../../images/character_skill/trailblazer_fire_skill6.webp"),
  },
};

export default CharacterSkillMain;
