const Material: any = {
  //add in 2.1.0-
  673758: require("../../images/material_icon/material_divine_amber.webp"),
  673753: require("../../images/material_icon/material_myriad_fruit.webp"),
  589817: require("../../images/material_icon/material_crystal_meteorites.webp"),
  874344: require("../../images/material_icon/material_scattered_stardust.webp"),
  589812: require("../../images/material_icon/material_nourishing_honey.webp"),
  874339: require("../../images/material_icon/material_alien_tree_seed.webp"),
  983280: require("../../images/material_icon/material_raging_heart.webp"),
  //add in 2.0.0
  635680: require("../../images/material_icon/material_borisin_teeth.webp"),
  920207: require("../../images/material_icon/material_lupitoxin_sawteeth.webp"),
  836266: require("../../images/material_icon/material_moon_madness_fang.webp"),
  549209: require("../../images/material_icon/material_dream_collection_component.webp"),
  633150: require("../../images/material_icon/material_dream_flow_valve.webp"),
  717091: require("../../images/material_icon/material_dream_making_engine.webp"),
  67221: require("../../images/material_icon/material_dream_fridge.webp"),
  549210: require("../../images/material_icon/material_tatters_of_thought.webp"),
  633151: require("../../images/material_icon/material_fragments_of_impression.webp"),
  717092: require("../../images/material_icon/material_shards_of_desires.webp"),
  351748: require("../../images/material_icon/material_dream_flamer.webp"),
  874346: require("../../images/material_icon/material_firmament_note.webp"),
  589819: require("../../images/material_icon/material_celestial_section.webp"),
  673760: require("../../images/material_icon/material_heavenly_melody.webp"),
  673759: require("../../images/material_icon/material_heaven_incinerator.webp"),
  874345: require("../../images/material_icon/material_fiery_spirit.webp"),
  589818: require("../../images/material_icon/material_starfire_essence.webp"),

  //星瓊
  900001: require("../../images/material_icon/material_stella_jade.webp"),
  //Lightcone EXP
  694487: require("../../images/material_icon/material_refined_aether.webp"),
  694488: require("../../images/material_icon/material_condensed_aether.webp"),
  694489: require("../../images/material_icon/material_sparse_aether.webp"),
  //add in 1.6.0
  470781: require("../../images/material_icon/material_past_evils_of_the_borehole_planet_disaster.webp"),

  29328: require("../../images/material_icon/material_credit.webp"),
  125435: require("../../images/material_icon/material_tracks_of_destiny.webp"),
  186254: require("../../images/material_icon/material_regret_of_infinite_ochema.webp"),
  409960: require("../../images/material_icon/material_travelers_guide.webp"),
  409961: require("../../images/material_icon/material_adventure_log.webp"),
  409962: require("../../images/material_icon/material_travel_encounters.webp"),
  549438: require("../../images/material_icon/material_extinguished_core.webp"),
  633379: require("../../images/material_icon/material_glimmering_core.webp"),
  635675: require("../../images/material_icon/material_key_of_inspiration.webp"),
  717320: require("../../images/material_icon/material_squirming_core.webp"),
  836261: require("../../images/material_icon/material_key_of_wisdom.webp"),
  866634: require("../../images/material_icon/material_netherworld_token.webp"),
  920202: require("../../images/material_icon/material_key_of_knowledge.webp"),
  267806: require("../../images/material_icon/material_ascendant_debris.webp"),
  549504: require("../../images/material_icon/material_immortal_scionette.webp"),
  633445: require("../../images/material_icon/material_immortal_aeroblossom.webp"),
  635671: require("../../images/material_icon/material_seed_of_abundance.webp"),
  717386: require("../../images/material_icon/material_immortal_lumintwig.webp"),
  836257: require("../../images/material_icon/material_flower_of_eternity.webp"),
  920198: require("../../images/material_icon/material_sprout_of_life.webp"),
  549503: require("../../images/material_icon/material_artifexs_module.webp"),
  633444: require("../../images/material_icon/material_artifexs_cogwheel.webp"),
  635670: require("../../images/material_icon/material_harmonic_tune.webp"),
  717385: require("../../images/material_icon/material_artifexs_gyreheart.webp"),
  836256: require("../../images/material_icon/material_stellaris_symphony.webp"),
  920197: require("../../images/material_icon/material_ancestral_hymn.webp"),
  67220: require("../../images/material_icon/material_gelid_chitin.webp"),
  635673: require("../../images/material_icon/material_shattered_blade.webp"),
  836259: require("../../images/material_icon/material_worldbreaker_blade.webp"),
  920200: require("../../images/material_icon/material_lifeless_blade.webp"),
  549407: require("../../images/material_icon/material_silvermane_badge.webp"),
  633348: require("../../images/material_icon/material_silvermane_insignia.webp"),
  635674: require("../../images/material_icon/material_arrow_of_the_beast_hunter.webp"),
  717289: require("../../images/material_icon/material_silvermane_medal.webp"),
  836260: require("../../images/material_icon/material_arrow_of_the_starchaser.webp"),
  920201: require("../../images/material_icon/material_arrow_of_the_demon_slayer.webp"),
  983279: require("../../images/material_icon/material_searing_steel_blade.webp"),
  635669: require("../../images/material_icon/material_obsidian_of_dread.webp"),
  836255: require("../../images/material_icon/material_obsidian_of_obsession.webp"),
  920196: require("../../images/material_icon/material_obsidian_of_desolation.webp"),
  468392: require("../../images/material_icon/material_suppressing_edict.webp"),
  351747: require("../../images/material_icon/material_nail_of_the_ape.webp"),
  635668: require("../../images/material_icon/material_endurance_of_bronze.webp"),
  836254: require("../../images/material_icon/material_safeguard_of_amber.webp"),
  920195: require("../../images/material_icon/material_oath_of_steel.webp"),
  151161: require("../../images/material_icon/material_shape_shifters_lightning_staff.webp"),
  549437: require("../../images/material_icon/material_thiefs_instinct.webp"),
  633378: require("../../images/material_icon/material_usurpers_scheme.webp"),
  717319: require("../../images/material_icon/material_conquerors_will.webp"),
  549408: require("../../images/material_icon/material_ancient_part.webp"),
  633349: require("../../images/material_icon/material_ancient_spindle.webp"),
  717290: require("../../images/material_icon/material_ancient_engine.webp"),
  866633: require("../../images/material_icon/material_broken_teeth_of_iron_wolf.webp"),
  468391: require("../../images/material_icon/material_golden_crown_of_the_past_shadow.webp"),
  985668: require("../../images/material_icon/material_destroyers_final_road.webp"),
  270195: require("../../images/material_icon/material_guardians_lament.webp"),
  351746: require("../../images/material_icon/material_void_cast_iron.webp"),
  151160: require("../../images/material_icon/material_lightning_crown_of_the_past_shadow.webp"),
  983278: require("../../images/material_icon/material_endotherm_chitin.webp"),
  267805: require("../../images/material_icon/material_storm_eye.webp"),
  67219: require("../../images/material_icon/material_horn_of_snow.webp"),
  782692: require("../../images/material_icon/material_enigmatic_ectostella.webp"),
};

export default Material;
