const Relic: any = {
  //Add in 2.1.0
  "Izumo Gensei and Takama Divine Realm": {
    icon1: require("../ornament_icon/izumo_gensei_and_takama_divine_realm_5.webp"),
    icon2: require("../ornament_icon/izumo_gensei_and_takama_divine_realm_6.webp"),
    pcIcon: require("../ornament_pcicon/izumo_gensei_and_takama_divine_realm.webp"),
  },
  "Sigonia, the Unclaimed Desolation": {
    icon1: require("../ornament_icon/sigonia_the_unclaimed_desolation_5.webp"),
    icon2: require("../ornament_icon/sigonia_the_unclaimed_desolation_6.webp"),
    pcIcon: require("../ornament_pcicon/sigonia_the_unclaimed_desolation.webp"),
  },
  //Add in 2.0.0
  "Pioneer Diver of Dead Waters": {
    icon1: require("../relic_icon/pioneer_diver_of_dead_waters_1.webp"),
    icon2: require("../relic_icon/pioneer_diver_of_dead_waters_2.webp"),
    icon3: require("../relic_icon/pioneer_diver_of_dead_waters_3.webp"),
    icon4: require("../relic_icon/pioneer_diver_of_dead_waters_4.webp"),
    pcIcon: require("../relic_pcicon/pioneer_diver_of_dead_waters.webp"),
  },
  "Watchmaker, Master of Dream Machinations": {
    icon1: require("../relic_icon/watchmaker_master_of_dream_machinations_1.webp"),
    icon2: require("../relic_icon/watchmaker_master_of_dream_machinations_2.webp"),
    icon3: require("../relic_icon/watchmaker_master_of_dream_machinations_3.webp"),
    icon4: require("../relic_icon/watchmaker_master_of_dream_machinations_4.webp"),
    pcIcon: require("../relic_pcicon/watchmaker_master_of_dream_machinations.webp"),
  },
  // Add in 1.6.0 and before
  "Passerby of Wandering Cloud": {
    icon1: require("../relic_icon/passerby_of_wandering_cloud_1.webp"),
    icon2: require("../relic_icon/passerby_of_wandering_cloud_2.webp"),
    icon3: require("../relic_icon/passerby_of_wandering_cloud_3.webp"),
    icon4: require("../relic_icon/passerby_of_wandering_cloud_4.webp"),
    pcIcon: require("../relic_pcicon/passerby_of_wandering_cloud.webp"),
  },
  "Musketeer of Wild Wheat": {
    icon1: require("../relic_icon/musketeer_of_wild_wheat_1.webp"),
    icon2: require("../relic_icon/musketeer_of_wild_wheat_2.webp"),
    icon3: require("../relic_icon/musketeer_of_wild_wheat_3.webp"),
    icon4: require("../relic_icon/musketeer_of_wild_wheat_4.webp"),
    pcIcon: require("../relic_pcicon/musketeer_of_wild_wheat.webp"),
  },
  "Knight of Purity Palace": {
    icon1: require("../relic_icon/knight_of_purity_palace_1.webp"),
    icon2: require("../relic_icon/knight_of_purity_palace_2.webp"),
    icon3: require("../relic_icon/knight_of_purity_palace_3.webp"),
    icon4: require("../relic_icon/knight_of_purity_palace_4.webp"),
    pcIcon: require("../relic_pcicon/knight_of_purity_palace.webp"),
  },
  "Hunter of Glacial Forest": {
    icon1: require("../relic_icon/hunter_of_glacial_forest_1.webp"),
    icon2: require("../relic_icon/hunter_of_glacial_forest_2.webp"),
    icon3: require("../relic_icon/hunter_of_glacial_forest_3.webp"),
    icon4: require("../relic_icon/hunter_of_glacial_forest_4.webp"),
    pcIcon: require("../relic_pcicon/hunter_of_glacial_forest.webp"),
  },
  "Champion of Streetwise Boxing": {
    icon1: require("../relic_icon/champion_of_streetwise_boxing_1.webp"),
    icon2: require("../relic_icon/champion_of_streetwise_boxing_2.webp"),
    icon3: require("../relic_icon/champion_of_streetwise_boxing_3.webp"),
    icon4: require("../relic_icon/champion_of_streetwise_boxing_4.webp"),
    pcIcon: require("../relic_pcicon/champion_of_streetwise_boxing.webp"),
  },
  "Guard of Wuthering Snow": {
    icon1: require("../relic_icon/guard_of_wuthering_snow_1.webp"),
    icon2: require("../relic_icon/guard_of_wuthering_snow_2.webp"),
    icon3: require("../relic_icon/guard_of_wuthering_snow_3.webp"),
    icon4: require("../relic_icon/guard_of_wuthering_snow_4.webp"),
    pcIcon: require("../relic_pcicon/guard_of_wuthering_snow.webp"),
  },
  "Firesmith of Lava-Forging": {
    icon1: require("../relic_icon/firesmith_of_lava_forging_1.webp"),
    icon2: require("../relic_icon/firesmith_of_lava_forging_2.webp"),
    icon3: require("../relic_icon/firesmith_of_lava_forging_3.webp"),
    icon4: require("../relic_icon/firesmith_of_lava_forging_4.webp"),
    pcIcon: require("../relic_pcicon/firesmith_of_lava_forging.webp"),
  },
  "Genius of Brilliant Stars": {
    icon1: require("../relic_icon/genius_of_brilliant_stars_1.webp"),
    icon2: require("../relic_icon/genius_of_brilliant_stars_2.webp"),
    icon3: require("../relic_icon/genius_of_brilliant_stars_3.webp"),
    icon4: require("../relic_icon/genius_of_brilliant_stars_4.webp"),
    pcIcon: require("../relic_pcicon/genius_of_brilliant_stars.webp"),
  },
  "Band of Sizzling Thunder": {
    icon1: require("../relic_icon/band_of_sizzling_thunder_1.webp"),
    icon2: require("../relic_icon/band_of_sizzling_thunder_2.webp"),
    icon3: require("../relic_icon/band_of_sizzling_thunder_3.webp"),
    icon4: require("../relic_icon/band_of_sizzling_thunder_4.webp"),
    pcIcon: require("../relic_pcicon/band_of_sizzling_thunder.webp"),
  },
  "Eagle of Twilight Line": {
    icon1: require("../relic_icon/eagle_of_twilight_line_1.webp"),
    icon2: require("../relic_icon/eagle_of_twilight_line_2.webp"),
    icon3: require("../relic_icon/eagle_of_twilight_line_3.webp"),
    icon4: require("../relic_icon/eagle_of_twilight_line_4.webp"),
    pcIcon: require("../relic_pcicon/eagle_of_twilight_line.webp"),
  },
  "Thief of Shooting Meteor": {
    icon1: require("../relic_icon/thief_of_shooting_meteor_1.webp"),
    icon2: require("../relic_icon/thief_of_shooting_meteor_2.webp"),
    icon3: require("../relic_icon/thief_of_shooting_meteor_3.webp"),
    icon4: require("../relic_icon/thief_of_shooting_meteor_4.webp"),
    pcIcon: require("../relic_pcicon/thief_of_shooting_meteor.webp"),
  },
  "Wastelander of Banditry Desert": {
    icon1: require("../relic_icon/wastelander_of_banditry_desert_1.webp"),
    icon2: require("../relic_icon/wastelander_of_banditry_desert_2.webp"),
    icon3: require("../relic_icon/wastelander_of_banditry_desert_3.webp"),
    icon4: require("../relic_icon/wastelander_of_banditry_desert_4.webp"),
    pcIcon: require("../relic_pcicon/wastelander_of_banditry_desert.webp"),
  },
  "Longevous Disciple": {
    icon1: require("../relic_icon/longevous_disciple_1.webp"),
    icon2: require("../relic_icon/longevous_disciple_2.webp"),
    icon3: require("../relic_icon/longevous_disciple_3.webp"),
    icon4: require("../relic_icon/longevous_disciple_4.webp"),
    pcIcon: require("../relic_pcicon/longevous_disciple.webp"),
  },
  "Messenger Traversing Hackerspace": {
    icon1: require("../relic_icon/messenger_traversing_hackerspace_1.webp"),
    icon2: require("../relic_icon/messenger_traversing_hackerspace_2.webp"),
    icon3: require("../relic_icon/messenger_traversing_hackerspace_3.webp"),
    icon4: require("../relic_icon/messenger_traversing_hackerspace_4.webp"),
    pcIcon: require("../relic_pcicon/messenger_traversing_hackerspace.webp"),
  },
  "The Ashblazing Grand Duke": {
    icon1: require("../relic_icon/the_ashblazing_grand_duke_1.webp"),
    icon2: require("../relic_icon/the_ashblazing_grand_duke_2.webp"),
    icon3: require("../relic_icon/the_ashblazing_grand_duke_3.webp"),
    icon4: require("../relic_icon/the_ashblazing_grand_duke_4.webp"),
    pcIcon: require("../relic_pcicon/the_ashblazing_grand_duke.webp"),
  },
  "Prisoner in Deep Confinement": {
    icon1: require("../relic_icon/prisoner_in_deep_confinement_1.webp"),
    icon2: require("../relic_icon/prisoner_in_deep_confinement_2.webp"),
    icon3: require("../relic_icon/prisoner_in_deep_confinement_3.webp"),
    icon4: require("../relic_icon/prisoner_in_deep_confinement_4.webp"),
    pcIcon: require("../relic_pcicon/prisoner_in_deep_confinement.webp"),
  },
  "Space Sealing Station": {
    icon1: require("../ornament_icon/space_sealing_station_5.webp"),
    icon2: require("../ornament_icon/space_sealing_station_6.webp"),
    pcIcon: require("../ornament_pcicon/space_sealing_station.webp"),
  },
  "Fleet of the Ageless": {
    icon1: require("../ornament_icon/fleet_of_the_ageless_5.webp"),
    icon2: require("../ornament_icon/fleet_of_the_ageless_6.webp"),
    pcIcon: require("../ornament_pcicon/fleet_of_the_ageless.webp"),
  },
  "Pan-Cosmic Commercial Enterprise": {
    icon1: require("../ornament_icon/pan_galactic_commercial_enterprise_5.webp"),
    icon2: require("../ornament_icon/pan_galactic_commercial_enterprise_6.webp"),
    pcIcon: require("../ornament_pcicon/pan_galactic_commercial_enterprise.webp"),
  },
  "Belobog of the Architects": {
    icon1: require("../ornament_icon/belobog_of_the_architects_5.webp"),
    icon2: require("../ornament_icon/belobog_of_the_architects_6.webp"),
    pcIcon: require("../ornament_pcicon/belobog_of_the_architects.webp"),
  },
  "Celestial Differentiator": {
    icon1: require("../ornament_icon/celestial_differentiator_5.webp"),
    icon2: require("../ornament_icon/celestial_differentiator_6.webp"),
    pcIcon: require("../ornament_pcicon/celestial_differentiator.webp"),
  },
  "Inert Salsotto": {
    icon1: require("../ornament_icon/inert_salsotto_5.webp"),
    icon2: require("../ornament_icon/inert_salsotto_6.webp"),
    pcIcon: require("../ornament_pcicon/inert_salsotto.webp"),
  },
  "Talia: Kingdom of Banditry": {
    icon1: require("../ornament_icon/talia_kingdom_of_banditry_5.webp"),
    icon2: require("../ornament_icon/talia_kingdom_of_banditry_6.webp"),
    pcIcon: require("../ornament_pcicon/talia_kingdom_of_banditry.webp"),
  },
  "Sprightly Vonwacq": {
    icon1: require("../ornament_icon/sprightly_vonwacq_5.webp"),
    icon2: require("../ornament_icon/sprightly_vonwacq_6.webp"),
    pcIcon: require("../ornament_pcicon/sprightly_vonwacq.webp"),
  },
  "Rutilant Arena": {
    icon1: require("../ornament_icon/rutilant_arena_5.webp"),
    icon2: require("../ornament_icon/rutilant_arena_6.webp"),
    pcIcon: require("../ornament_pcicon/rutilant_arena.webp"),
  },
  "Broken Keel": {
    icon1: require("../ornament_icon/broken_keel_5.webp"),
    icon2: require("../ornament_icon/broken_keel_6.webp"),
    pcIcon: require("../ornament_pcicon/broken_keel.webp"),
  },
  "Firmament Frontline: Glamoth": {
    icon1: require("../ornament_icon/firmament_frontline_glamoth_5.webp"),
    icon2: require("../ornament_icon/firmament_frontline_glamoth_6.webp"),
    pcIcon: require("../ornament_pcicon/firmament_frontline_glamoth.webp"),
  },
  "Penacony, Land of the Dreams": {
    icon1: require("../ornament_icon/penacony_land_of_the_dreams_5.webp"),
    icon2: require("../ornament_icon/penacony_land_of_the_dreams_6.webp"),
    pcIcon: require("../ornament_pcicon/penacony_land_of_the_dreams.webp"),
  },
};

export default Relic;
