/**
 * * 崩鐵角色稱標準名稱
 * * 作為 Stargazer 的角色 ID
 */
export type CharacterName =
  | "Dr. Ratio"
  | "Ruan Mei"
  | "Xueyi"
  | "Argenti"
  | "Huohuo"
  | "Hanya"
  | "Jingliu"
  | "Topaz & Numby"
  | "Guinaifen"
  | "Dan Heng • Imbibitor Lunae"
  | "Fu Xuan"
  | "Lynx"
  | "Kafka"
  | "Blade"
  | "Luka"
  | "Yukong"
  | "Luocha"
  | "Silver Wolf"
  | "Arlan"
  | "Asta"
  | "Bailu"
  | "Bronya"
  | "Clara"
  | "Dan Heng"
  | "Gepard"
  | "Herta"
  | "Himeko"
  | "Hook"
  | "Jing Yuan"
  | "March 7th"
  | "Natasha"
  | "Pela"
  | "Qingque"
  | "Sampo"
  | "Seele"
  | "Serval"
  | "Sushang"
  | "Tingyun"
  | "Welt"
  | "Yanqing"
  | "Trailblazer Boy (Physical)"
  | "Trailblazer Girl (Physical)"
  | "Trailblazer Boy (Fire)"
  | "Trailblazer Girl (Fire)";
