const LightconeName = {
  //Add in 2.1.0
  "inherently-unjust-destiny": "Inherently Unjust Destiny",
  "along-the-passing-shore": "Along the Passing Shore",
  "concert-for-two": "Concert for Two",
  //Add in 2.0.0
  "earthly-escapade": "Earthly Escapade",
  "reforged-remembrance": "Reforged Remembrance",
  "what-is-real": "What Is Real?",
  "flames-afar": "Flames Afar",
  "destinys-threads-forewoven": "Destiny's Threads Forewoven",
  "the-day-the-cosmos-fell": "The Day The Cosmos Fell",
  "its-showtime": "It's Showtime",
  "indelible-promise": "Indelible Promise",
  "final-victor": "Final Victor",
  "dreamville-adventure": "Dreamville Adventure",

  //Add in 1.6.0
  "baptism-of-pure-thought": "Baptism of Pure Thought",
  "past-self-in-mirror": "Past Self in Mirror",

  //Add in 1.5.0
  "night-of-fright": "Night of Fright",
  "an-instant-before-a-gaze": "An Instant Before A Gaze",
  "hey-over-here": "Hey, Over Here",

  //Add in 1.4.0
  "i-shall-be-my-own-sword": "I Shall Be My Own Sword",
  "worrisome-blissful": "Worrisome, Blissful",

  //Add in 1.3.0
  "she-already-shut-her-eyes": "She Already Shut Her Eyes",
  "brighter-than-the-sun": "Brighter Than the Sun",
  "solitary-healing": "Solitary Healing",

  //Add in 1.2.0
  "patience-is-all-you-need": "Patience Is All You Need",
  "the-unreachable-side": "The Unreachable Side",

  "a-secret-vow": "A Secret Vow",
  adversarial: "Adversarial",
  amber: "Amber",
  arrows: "Arrows",
  "before-dawn": "Before Dawn",
  "before-the-tutorial-mission-starts": "Before the Tutorial Mission Starts",
  "but-the-battle-isnt-over": "But the Battle Isn't Over",
  "carve-the-moon-weave-the-clouds": "Carve the Moon, Weave the Clouds",
  chorus: "Chorus",
  "collapsing-sky": "Collapsing Sky",
  cornucopia: "Cornucopia",
  "cruising-in-the-stellar-sea": "Cruising in the Stellar Sea",
  "dance-dance-dance": "Dance! Dance! Dance!",
  "darting-arrow": "Darting Arrow",
  "data-bank": "Data Bank",
  "day-one-of-my-new-life": "Day One of My New Life",
  defense: "Defense",
  "echoes-of-the-coffin": "Echoes of the Coffin",
  "eyes-of-the-prey": "Eyes of the Prey",
  fermata: "Fermata",
  "fine-fruit": "Fine Fruit",
  "geniuses-repose": "Geniuses' Repose",
  "good-night-and-sleep-well": "Good Night and Sleep Well",
  "hidden-shadow": "Hidden Shadow",
  "in-the-name-of-the-world": "In the Name of the World",
  "in-the-night": "In the Night",
  "incessant-rain": "Incessant Rain",
  "landaus-choice": "Landau's Choice",
  loop: "Loop",
  "make-the-world-clamor": "Make the World Clamor",
  mediation: "Mediation",
  "memories-of-the-past": "Memories of the Past",
  "meshing-cogs": "Meshing Cogs",
  "moment-of-victory": "Moment of Victory",
  multiplication: "Multiplication",
  "mutual-demise": "Mutual Demise",
  "night-on-the-milky-way": "Night on the Milky Way",
  "nowhere-to-run": "Nowhere to Run",
  "on-the-fall-of-an-aeon": "On the Fall of an Aeon",
  "only-silence-remains": "Only Silence Remains",
  passkey: "Passkey",
  "past-and-future": "Past and Future",
  "perfect-timing": "Perfect Timing",
  pioneering: "Pioneering",
  "planetary-rendezvous": "Planetary Rendezvous",
  "post-op-conversation": "Post-Op Conversation",
  "quid-pro-quo": "Quid Pro Quo",
  "resolution-shines-as-pearls-of-sweat":
    "Resolution Shines As Pearls of Sweat",
  "return-to-darkness": "Return to Darkness",
  "river-flows-in-spring": "River Flows in Spring",
  sagacity: "Sagacity",
  "shared-feeling": "Shared Feeling",
  "shattered-home": "Shattered Home",
  "sleep-like-the-dead": "Sleep Like the Dead",
  "something-irreplaceable": "Something Irreplaceable",
  "subscribe-for-more": "Subscribe for More!",
  swordplay: "Swordplay",
  "texture-of-memories": "Texture of Memories",
  "the-birth-of-the-self": "The Birth of the Self",
  "the-moles-welcome-you": "The Moles Welcome You",
  "the-seriousness-of-breakfast": "The Seriousness of Breakfast",
  "this-is-me": "This Is Me!",
  "time-waits-for-no-one": "Time Waits for No One",
  "today-is-another-peaceful-day": "Today Is Another Peaceful Day",
  "trend-of-the-universal-market": "Trend of the Universal Market",
  "under-the-blue-sky": "Under the Blue Sky",
  void: "Void",
  "warmth-shortens-cold-nights": "Warmth Shortens Cold Nights",
  "we-are-wildfire": "We Are Wildfire",
  "we-will-meet-again": "We Will Meet Again",
  "woof-walk-time": "Woof! Walk Time!",
};
export default LightconeName;
