export const longStrings = {
    PublicCharDesc: "为了保障安全性和用户权益，我们通过用户的设备（客户端），而非透过服务器来更新 hoyolab 角色数据。这意味着如果用户一段时间不使用 Stargazer，可能会导致他们的角色数量、活跃天数、达成成就和忘却之庭数据存在差异。请注意，这些数据仅供参考，不具有绝对准确性。",
    TrailblazerNotiTaggedU: "玩家 ${1} 在【${2}讨论串】提及了您！快来参与讨论吧。",
    UIDOnlySupportFullUID: "仅支持查询完整UID，不支持查询昵称或部分UID",
    SelectServerAndPasteCookies: "请选择服务器并贴上 Cookies。",
    LoginViaPCToGetCookies: "请使用计算机登入 hoyolab / 米游社，按 F12 开启开发人员面板-> 应用程序 -> Cookies, 把包含 ltuid_v2、ltoken_v2、account_id_v2、cookie_token_v2、account_mid_v2 和 ltmid_v2 贴上。请注意，此选项主要为开发人员设计。Stargazer 建议您在非不得已的情况下不要使用这一选项，以免增加复杂度。",
    CommentOverLimit: "输入超过最大值上限（200字元），请减少输入再发布。",
    DonationRemoveAds: "可以透过捐赠或邀请他人移除广告",
    AboutTheAppContent:"<h2>关于应用</h2><div>Stargazer 2 是由 Coding Band 团队开发的一款星铁第三方助手应用，提供诸如练度查询，角色图鉴，战绩查询和排行榜等功能。<br>我们旨在打造一款原生、移动端体验的星铁助手 App，提供更方便和流畅的使用体验。</div><br><h2>关于团队</h2><div>Coding Band 是一个专注于开发具实用性、钻研软件内艺术和趣味性的开发团队，目前由三位核心成员组成：</div><div><li>2O48：UI/UX 设计师，美术把关</li><li>Dalufish：首席工程师，全端开发</li><li>Voc-夜芷冰：项目负责人，全端开发</li></div><h2>特别感谢</h2><div>特别感谢明治及所有封测测试员，在封测期协助我们完善 Stargazer 2：<br>jedudu<br>yi_9487<br>appledush#0218<br>shiroweaver<br>_7475<br>rxin.66<br>rover5205<br>rudmon<br>.yanyi<br>mo_yc<br>ryouendragon3369<br>jonahs0202<br>mashujiu<br>yangyangxd<br>sava_tw<br>日轮#1577<br>.yangqin<br>sakura_snow.0w0<br>professionalwindowsexpert<br>dreamawake<br>_d_evil_<br>whitykun<br><br>没有你们 Stargazer 2 根本不可能在两个月内发布正式版 :D<br></div><h2>温馨提醒</h2><div>请注意：本项目及应用程序并不属于 miHoYo Co., Ltd. 且并未获得其认可。Stargazer 2（星穹观星者2）仅为一款由粉丝自行开发之数据提供 App，本应用程序所提供的数据只作参考用途。 不会对其所载任何数据的准确性及完整作任何程度保证。<br><br>「星穹观星者 2」项目内使用之各素材版权归该版权所有者拥有。<br>「星穹观星者 2」项目代码著作权归 Coding Band 所有。</div><br>部分在本项目使用的素材来自以下网站<br>https://starrailstation.com/<br><br>https://github.com/reko-beep/hsr-data<br><br>https://honkai-star-rail.fandom.com/wiki/Honkai:_Star_Rail_Wiki<br><br>https://wiki.biligame.com/sr/首页<br><br>https://www.prydwen.gg/star-rail<br><br>https://api.mihomo.me/<br><br>https://github.com/Mar-7th"
}