const CharacterName = {
  //add in 1.6.0
  "dr-ratio": "Dr. Ratio",
  "ruan-mei": "Ruan Mei",
  xueyi: "Xueyi",

  //add in 1.5.0 or before
  argenti: "Argenti",
  huohuo: "Huohuo",
  hanya: "Hanya",
  jingliu: "Jingliu",
  topaz: "Topaz & Numby",
  guinaifen: "Guinaifen",
  "imbibitor-lunae": "Dan Heng • Imbibitor Lunae",
  "fu-xuan": "Fu Xuan",
  lynx: "Lynx",
  kafka: "Kafka",
  blade: "Blade",
  luka: "Luka",
  yukong: "Yukong",
  luocha: "Luocha",
  "silver-wolf": "Silver Wolf",
  arlan: "Arlan",
  asta: "Asta",
  bailu: "Bailu",
  bronya: "Bronya",
  clara: "Clara",
  "dan-heng": "Dan Heng",
  gepard: "Gepard",
  herta: "Herta",
  himeko: "Himeko",
  hook: "Hook",
  "jing-yuan": "Jing Yuan",
  "march-7th": "March 7th",
  natasha: "Natasha",
  pela: "Pela",
  qingque: "Qingque",
  sampo: "Sampo",
  seele: "Seele",
  serval: "Serval",
  sushang: "Sushang",
  tingyun: "Tingyun",
  welt: "Welt",
  yanqing: "Yanqing",
  "trailblazer-fire": "Trailblazer Girl (Fire)",
  "trailblazer-physical": "Trailblazer Girl (Physical)",
};
export default CharacterName;
