const officalRelicId: any = {
  101: "Passerby of Wandering Cloud",
  102: "Musketeer of Wild Wheat",
  103: "Knight of Purity Palace",
  104: "Hunter of Glacial Forest",
  105: "Champion of Streetwise Boxing",
  106: "Guard of Wuthering Snow",
  107: "Firesmith of Lava-Forging",
  108: "Genius of Brilliant Stars",
  109: "Band of Sizzling Thunder",
  110: "Eagle of Twilight Line",
  111: "Thief of Shooting Meteor",
  112: "Wastelander of Banditry Desert",
  113: "Longevous Disciple",
  114: "Messenger Traversing Hackerspace",
  115: "The Ashblazing Grand Duke",
  116: "Prisoner in Deep Confinement",
  117: "Pioneer Diver of Dead Waters",
  118: "Watchmaker, Master of Dream Machinations",
  301: "Space Sealing Station",
  302: "Fleet of the Ageless",
  303: "Pan-Cosmic Commercial Enterprise",
  304: "Belobog of the Architects",
  305: "Celestial Differentiator",
  306: "Inert Salsotto",
  307: "Talia: Kingdom of Banditry",
  308: "Sprightly Vonwacq",
  309: "Rutilant Arena",
  310: "Broken Keel",
  311: "Firmament Frontline: Glamoth",
  312: "Penacony, Land of the Dreams",
};

export default officalRelicId;
